#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Roles/_CreateOrEdit.cshtml")]
    public partial class _Areas_Admin_Views_Roles__CreateOrEdit_cshtml : System.Web.Mvc.WebViewPage<WebSQL.Areas.Admin.Controllers.UserCreateView>
    {
        public _Areas_Admin_Views_Roles__CreateOrEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
Write(Html.Hidden("Id", Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>UserName</label>\r\n    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"UserName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 200), Tuple.Create("\"", 223)
            
            #line 6 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 208), Tuple.Create<System.Object, System.Int32>(Model.UserName
            
            #line default
            #line hidden
, 208), false)
);

WriteLiteral(" required />\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>UserEmail</label>\r\n    <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"Email\"");

WriteAttribute("value", Tuple.Create(" value=\"", 359), Tuple.Create("\"", 379)
            
            #line 10 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 367), Tuple.Create<System.Object, System.Int32>(Model.Email
            
            #line default
            #line hidden
, 367), false)
);

WriteLiteral(" required />\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>Password</label>\r\n    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"Password\"");

WriteAttribute("value", Tuple.Create(" value=\"", 520), Tuple.Create("\"", 543)
            
            #line 14 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 528), Tuple.Create<System.Object, System.Int32>(Model.Password
            
            #line default
            #line hidden
, 528), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>Confirm Password</label>\r\n    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"ConfirmPassword\"");

WriteAttribute("value", Tuple.Create(" value=\"", 690), Tuple.Create("\"", 720)
            
            #line 18 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 698), Tuple.Create<System.Object, System.Int32>(Model.ConfirmPassword
            
            #line default
            #line hidden
, 698), false)
);

WriteLiteral(" />\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>Roles</label>\r\n    <select");

WriteLiteral(" name=\"SelectedRoles\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" size=\"5\"");

WriteLiteral(" multiple=\"\"");

WriteLiteral(">\r\n        <option");

WriteLiteral(" value=\"\"");

WriteLiteral(">--</option>\r\n");

            
            #line 24 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
         foreach (var item in Model.Roles)
        {

            
            #line default
            #line hidden
WriteLiteral("            <option");

WriteAttribute("value", Tuple.Create(" value=\"", 975), Tuple.Create("\"", 991)
            
            #line 26 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 983), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 983), false)
);

WriteLiteral(" ");

            
            #line 26 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
                                 Write(Model.SelectedRoles.Contains(item.Id) ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 26 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
                                                                                           Write(item.RoleDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 27 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n</div>\r\n\r\n");

            
            #line 31 "..\..\Areas\Admin\Views\Roles\_CreateOrEdit.cshtml"
   Html.RenderPartial("AdminInputs/_PropertiesEdit", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success waves-effect waves-light m-r-10\"");

WriteLiteral(">Submit</button>");

        }
    }
}
#pragma warning restore 1591
