#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Roles/RoleList.cshtml")]
    public partial class _Areas_Admin_Views_Roles_RoleList_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<WebSQL.Areas.Admin.Controllers.RoleNameAndUser>>
    {
        public _Areas_Admin_Views_Roles_RoleList_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
  
    ViewBag.Title = "RoleList";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"create-role-model\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"myModalLabel\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n            <form");

WriteAttribute("action", Tuple.Create(" action=\"", 323), Tuple.Create("\"", 391)
            
            #line 9 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
, Tuple.Create(Tuple.Create("", 332), Tuple.Create<System.Object, System.Int32>(Url.Action("CreateRole","Roles",new { @area=G.AdminPath })
            
            #line default
            #line hidden
, 332), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">x</span></button>\r\n                    <h4");

WriteLiteral(" class=\"modal-title\"");

WriteLiteral(" id=\"myModalLabel\"");

WriteLiteral(">Create Role</h4>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <label>Role Admin Name</label>\r\n                      " +
"  <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Name\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(">\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\r\n                    <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Save</button>\r\n                </div>\r\n            </form>\r\n\r\n        </div>\r\n  " +
"  </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"row clearfix\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(">\r\n                <h2>\r\n                    Roles\r\n                </h2>\r\n      " +
"          <br />\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info waves-effect m-r-20\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" data-target=\"#create-role-model\"");

WriteLiteral(">\r\n                    Create Role\r\n                </button>\r\n            </div>" +
"\r\n            <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" id=\"demo-foo-filtering\"");

WriteLiteral(" class=\"table table-bordered table-hover toggle-circle\"");

WriteLiteral(" data-page-size=\"7\"");

WriteLiteral(">\r\n                    <thead>\r\n                        <tr>\r\n                   " +
"         <th");

WriteLiteral(" data-toggle=\"true\"");

WriteLiteral(">Role Name</th>\r\n                            <th>Users</th>\r\n                    " +
"        <th>Options</th>\r\n                        </tr>\r\n                    </t" +
"head>\r\n                    <tbody>\r\n");

            
            #line 52 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
                         foreach (var item in Model)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <tr>\r\n                                <td>");

            
            #line 55 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
                               Write(item.RoleDisplayName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>");

            
            #line 56 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
                               Write(item.Users);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                                <td>\r\n                                    " +
"<form");

WriteAttribute("action", Tuple.Create(" action=\"", 2540), Tuple.Create("\"", 2608)
            
            #line 58 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
, Tuple.Create(Tuple.Create("", 2549), Tuple.Create<System.Object, System.Int32>(Url.Action("DeleteRole","Roles",new { @area=G.AdminPath })
            
            #line default
            #line hidden
, 2549), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"id\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2696), Tuple.Create("\"", 2712)
            
            #line 59 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
, Tuple.Create(Tuple.Create("", 2704), Tuple.Create<System.Object, System.Int32>(item.Id
            
            #line default
            #line hidden
, 2704), false)
);

WriteLiteral(" />\r\n                                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-danger btn-group\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(@">
                                            Delete Role
                                        </button>
                                    </form>
                                    
                                </td>
                            </tr>
");

            
            #line 67 "..\..\Areas\Admin\Views\Roles\RoleList.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                    <tfoot>\r\n                      " +
"  <tr>\r\n                            <td");

WriteLiteral(" colspan=\"5\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"text-right\"");

WriteLiteral(">\r\n                                    <ul");

WriteLiteral(" class=\"pagination\"");

WriteLiteral("></ul>\r\n                                </div>\r\n                            </td>" +
"\r\n                        </tr>\r\n                    </tfoot>\r\n                <" +
"/table>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/admin-lib/plugins/footable/js/footable.all.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/admin-lib/plugins/footable/js/footable.min.js\"");

WriteLiteral("></script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
