#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/Contents/_ContentTable.cshtml")]
    public partial class _Areas_Admin_Views_Shared_Contents__ContentTable_cshtml : System.Web.Mvc.WebViewPage<ContentTableView>
    {
        public _Areas_Admin_Views_Shared_Contents__ContentTable_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script>\r\n    window.contents = {};\r\n    contents.clients = [\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
        
            
            #line default
            #line hidden
            
            #line 5 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
         foreach(var item in Model.Contents)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            {\r\n            ");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n\r\n                \"id\": \"");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                  Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                \"Name\": \"");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                    Write(item.Title);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n            ");

WriteLiteral("\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
            foreach(var k in Model.Keys)
            {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("\r\n                    \"");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                Write(k.Key);

            
            #line default
            #line hidden
WriteLiteral("\": \"");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                          Write(item.GetValueByKey(k.Key));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                ");

WriteLiteral("\r\n");

            
            #line 21 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            },\r\n            ");

WriteLiteral("\r\n");

            
            #line 25 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("            ];\r\n    ! function (document, window, $) {\r\n        \"use strict\";\r\n  " +
"      var Site = window.Site;\r\n        $(document).ready(function ($) {\r\n\r\n     " +
"   }), jsGrid.setDefaults({\r\n            tableClass: \"jsgrid-table table table-s" +
"triped table-hover\"\r\n        }), jsGrid.setDefaults(\"text\", {\r\n            _crea" +
"teTextBox: function () {\r\n                return $(\"<input>\").attr(\"type\", \"text" +
"\").attr(\"class\", \"form-control input-sm\")\r\n            }\r\n        }), jsGrid.set" +
"Defaults(\"number\", {\r\n            _createTextBox: function () {\r\n               " +
" return $(\"<input>\").attr(\"type\", \"number\").attr(\"class\", \"form-control input-sm" +
"\")\r\n            }\r\n        }), jsGrid.setDefaults(\"textarea\", {\r\n            _cr" +
"eateTextBox: function () {\r\n                return $(\"<input>\").attr(\"type\", \"te" +
"xtarea\").attr(\"class\", \"form-control\")\r\n            }\r\n        }), jsGrid.setDef" +
"aults(\"control\", {\r\n            _createGridButton: function (cls, tooltip, click" +
"Handler) {\r\n                var grid = this._grid;\r\n                return $(\"<b" +
"utton>\").addClass(this.buttonClass).addClass(cls).attr({\r\n                    ty" +
"pe: \"button\",\r\n                    title: tooltip\r\n                }).on(\"click\"" +
", function (e) {\r\n                    clickHandler(grid, e)\r\n                })\r" +
"\n            }\r\n        }),\r\n            function () {\r\n                $(\"#stat" +
"icgrid\").jsGrid({\r\n                    height: \"500px\",\r\n                    wid" +
"th: \"100%\",\r\n                    sorting: !0,\r\n                    paging: !0,\r\n" +
"                    data: contents.clients,\r\n                    rowClick: funct" +
"ion(b){\r\n");

WriteLiteral("                        ");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                   Write(Html.Raw(Model.RowClickFunction));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    },\r\n                    fields: [{\r\n                       " +
" name: \"Name\",\r\n                        type: \"text\",\r\n                        w" +
"idth: 150\r\n                    }\r\n");

            
            #line 72 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 72 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                         foreach(var k in Model.Keys)
                        {

            
            #line default
            #line hidden
WriteLiteral("                          ");

WriteLiteral("\r\n                        , {\r\n                            name: \"");

            
            #line 76 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                              Write(k.Key);

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                            type: \"text\",\r\n                            width:" +
" 100\r\n                        }\r\n\r\n                          ");

WriteLiteral("\r\n");

            
            #line 82 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTable.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    ]\r\n                })\r\n            }(),\r\n            functi" +
"on () {\r\n                var MyDateField = function (config) {\r\n                " +
"    jsGrid.Field.call(this, config)\r\n                };\r\n                MyDateF" +
"ield.prototype = new jsGrid.Field({\r\n                    sorter: function (date1" +
", date2) {\r\n                        return new Date(date1) - new Date(date2)\r\n  " +
"                  },\r\n                    itemTemplate: function (value) {\r\n    " +
"                    return new Date(value).toDateString()\r\n                    }" +
",\r\n                    insertTemplate: function () {\r\n                        if" +
" (!this.inserting) return \"\";\r\n                        var $result = this.insert" +
"Control = this._createTextBox();\r\n                        return $result\r\n      " +
"              },\r\n                    editTemplate: function (value) {\r\n        " +
"                if (!this.editing) return this.itemTemplate(value);\r\n           " +
"             var $result = this.editControl = this._createTextBox();\r\n          " +
"              return $result.val(value), $result\r\n                    },\r\n      " +
"              insertValue: function () {\r\n                        return this.in" +
"sertControl.datepicker(\"getDate\")\r\n                    },\r\n                    e" +
"ditValue: function () {\r\n                        return this.editControl.datepic" +
"ker(\"getDate\")\r\n                    },\r\n                    _createTextBox: func" +
"tion () {\r\n                        return $(\"<input>\").attr(\"type\", \"text\").addC" +
"lass(\"form-control input-sm\").datepicker({\r\n                            autoclos" +
"e: !0\r\n                        })\r\n                    }\r\n                }), js" +
"Grid.fields.myDateField = MyDateField\r\n            }()\r\n    }(document, window, " +
"jQuery);\r\n\r\n    function deleteCurrent() {\r\n        swal({\r\n            title: \"" +
"Confirm delete content?\",\r\n            text: \"You will delete this content and a" +
"ll other content under it. and will not recovered\",\r\n            type: \"warning\"" +
",\r\n            showCancelButton: true,\r\n            confirmButtonColor: \"#DD6B55" +
"\",\r\n            confirmButtonText: \"Yes, delete it!\",\r\n            cancelButtonT" +
"ext: \"No, cancel plx!\",\r\n            closeOnConfirm: false,\r\n            closeOn" +
"Cancel: false\r\n        }, function (isConfirm) {\r\n            if (isConfirm) {\r\n" +
"                swal(\"Deleted!\", \"Content has been deleted\", \"success\");\r\n      " +
"          $(\"#ContentDeleteForm\").submit();\r\n            } else {\r\n             " +
"   swal(\"Cancelled\", \"Canceled\", \"error\");\r\n            }\r\n        });\r\n    }\r\n<" +
"/script>\r\n");

        }
    }
}
#pragma warning restore 1591
