#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_js.cshtml")]
    public partial class _Areas_Admin_Views_Shared__js_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__js_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- CORE PLUGIN JS -->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 32), Tuple.Create("\"", 78)
, Tuple.Create(Tuple.Create("", 38), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery/jquery.min.js")
, 38), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 98), Tuple.Create("\"", 149)
, Tuple.Create(Tuple.Create("", 104), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap/js/bootstrap.js")
, 104), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 169), Tuple.Create("\"", 224)
, Tuple.Create(Tuple.Create("", 175), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/modernizr/modernizr.custom.js")
, 175), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 244), Tuple.Create("\"", 299)
, Tuple.Create(Tuple.Create("", 250), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/screenfull/dist/screenfull.js")
, 250), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 319), Tuple.Create("\"", 384)
, Tuple.Create(Tuple.Create("", 325), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jQuery-Storage-API/jquery.storageapi.js")
, 325), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 404), Tuple.Create("\"", 468)
, Tuple.Create(Tuple.Create("", 410), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-slimscroll/jquery.slimscroll.js")
, 410), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 488), Tuple.Create("\"", 533)
, Tuple.Create(Tuple.Create("", 494), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/node-waves/waves.js")
, 494), false)
);

WriteLiteral("></script>\r\n\r\n<!--THIS PAGE LEVEL JS-->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 582), Tuple.Create("\"", 645)
, Tuple.Create(Tuple.Create("", 588), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/jquery.dataTables.js")
, 588), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 665), Tuple.Create("\"", 749)
, Tuple.Create(Tuple.Create("", 671), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js")
, 671), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 769), Tuple.Create("\"", 855)
, Tuple.Create(Tuple.Create("", 775), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js")
, 775), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 875), Tuple.Create("\"", 956)
, Tuple.Create(Tuple.Create("", 881), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/buttons.flash.min.js")
, 881), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 976), Tuple.Create("\"", 1049)
, Tuple.Create(Tuple.Create("", 982), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/jszip.min.js")
, 982), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1069), Tuple.Create("\"", 1144)
, Tuple.Create(Tuple.Create("", 1075), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/pdfmake.min.js")
, 1075), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1164), Tuple.Create("\"", 1237)
, Tuple.Create(Tuple.Create("", 1170), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/vfs_fonts.js")
, 1170), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1257), Tuple.Create("\"", 1338)
, Tuple.Create(Tuple.Create("", 1263), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/buttons.html5.min.js")
, 1263), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1358), Tuple.Create("\"", 1439)
, Tuple.Create(Tuple.Create("", 1364), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/buttons.print.min.js")
, 1364), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1459), Tuple.Create("\"", 1546)
, Tuple.Create(Tuple.Create("", 1465), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/dataTables.keyTable.min.js" +
"")
, 1465), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1566), Tuple.Create("\"", 1655)
, Tuple.Create(Tuple.Create("", 1572), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/dataTables.responsive.min." +
"js")
, 1572), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1675), Tuple.Create("\"", 1763)
, Tuple.Create(Tuple.Create("", 1681), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/responsive.bootstrap.min.j" +
"s")
, 1681), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1783), Tuple.Create("\"", 1870)
, Tuple.Create(Tuple.Create("", 1789), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/dataTables.scroller.min.js" +
"")
, 1789), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 1890), Tuple.Create("\"", 1980)
, Tuple.Create(Tuple.Create("", 1896), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/extensions/export/dataTables.fixedHeader.min" +
".js")
, 1896), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2002), Tuple.Create("\"", 2060)
, Tuple.Create(Tuple.Create("", 2008), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-countto/jquery.countTo.js")
, 2008), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2080), Tuple.Create("\"", 2133)
, Tuple.Create(Tuple.Create("", 2086), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/masonry/masonry.pkgd.min.js")
, 2086), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2153), Tuple.Create("\"", 2215)
, Tuple.Create(Tuple.Create("", 2159), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-sparkline/jquery.sparkline.js")
, 2159), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2303), Tuple.Create("\"", 2351)
, Tuple.Create(Tuple.Create("", 2309), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/raphael/raphael.min.js")
, 2309), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2371), Tuple.Create("\"", 2419)
, Tuple.Create(Tuple.Create("", 2377), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/masonry/masonry.min.js")
, 2377), false)
);

WriteLiteral("></script>\r\n\r\n<!--Chat js-->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2457), Tuple.Create("\"", 2508)
, Tuple.Create(Tuple.Create("", 2463), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/assets/js/custom.js")
, 2463), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2551), Tuple.Create("\"", 2601)
, Tuple.Create(Tuple.Create("", 2557), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/chatjs/lightbox.js")
, 2557), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2644), Tuple.Create("\"", 2695)
, Tuple.Create(Tuple.Create("", 2650), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/chatjs/dashboard.js")
, 2650), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2738), Tuple.Create("\"", 2786)
, Tuple.Create(Tuple.Create("", 2744), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/chatjs/custom.js")
, 2744), false)
);

WriteLiteral("></script>\r\n<!-- #End# Chat js-->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2829), Tuple.Create("\"", 2883)
, Tuple.Create(Tuple.Create("", 2835), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/sweetalert/sweetalert.min.js")
, 2835), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2903), Tuple.Create("\"", 2945)
, Tuple.Create(Tuple.Create("", 2909), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/js/pages/index.js")
, 2909), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2967), Tuple.Create("\"", 3011)
, Tuple.Create(Tuple.Create("", 2973), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/momentjs/moment.js")
, 2973), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3031), Tuple.Create("\"", 3130)
, Tuple.Create(Tuple.Create("", 3037), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datet" +
"imepicker.js")
, 3037), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3150), Tuple.Create("\"", 3225)
, Tuple.Create(Tuple.Create("", 3156), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/boootstrap-datepicker/bootstrap-datepicker.min.js")
, 3156), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3245), Tuple.Create("\"", 3327)
, Tuple.Create(Tuple.Create("", 3251), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-datetime-picker/js/bootstrap-datetimepicker.js")
, 3251), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3347), Tuple.Create("\"", 3420)
, Tuple.Create(Tuple.Create("", 3353), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-timepicker/js/bootstrap-timepicker.js")
, 3353), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3440), Tuple.Create("\"", 3504)
, Tuple.Create(Tuple.Create("", 3446), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-daterange/daterangepicker.js")
, 3446), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3524), Tuple.Create("\"", 3570)
, Tuple.Create(Tuple.Create("", 3530), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/ckeditor/ckeditor.js")
, 3530), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3590), Tuple.Create("\"", 3651)
, Tuple.Create(Tuple.Create("", 3596), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-spinner/js/jquery.spinner.js")
, 3596), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3671), Tuple.Create("\"", 3739)
, Tuple.Create(Tuple.Create("", 3677), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-tagsinput/bootstrap-tagsinput.js")
, 3677), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3759), Tuple.Create("\"", 3837)
, Tuple.Create(Tuple.Create("", 3765), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-selectsplitter/bootstrap-selectsplitter.js")
, 3765), false)
);

WriteLiteral("></script>\r\n\r\n<!-- LAYOUT JS -->\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3879), Tuple.Create("\"", 3914)
, Tuple.Create(Tuple.Create("", 3885), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/js/demo.js")
, 3885), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 3934), Tuple.Create("\"", 3971)
, Tuple.Create(Tuple.Create("", 3940), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/js/layout.js")
, 3940), false)
);

WriteLiteral("></script>\r\n\r\n");

WriteLiteral("\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
