#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_ModelFormViewCore.cshtml")]
    public partial class _Areas_Admin_Views_Shared__ModelFormViewCore_cshtml : System.Web.Mvc.WebViewPage<SDHC.Common.Entity.Models.ModelPostModel>
    {
        public _Areas_Admin_Views_Shared__ModelFormViewCore_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
  
  var randomKey = Guid.NewGuid().ToString().Replace('-', '_');

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("Id", Model.Id, new { @id = "Id" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("FullType", Model.FullType, new { @id = "FullType" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("ThisAssembly", Model.ThisAssembly, new { @id = "ThisAssembly" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("PostUrl", Model.PostUrl, new { @id = "PostUrl" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("PostReturnUrl", Model.PostReturnUrl, new { @id = "PostReturnUrl" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("IsPostAjax", Model.IsPostAjax, new { @id = "IsPostAjax" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("PostBeforeMethod", Model.PostBeforeMethod, new { @id = "PostBeforeMethod" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("PostResponseMethod", Model.PostResponseMethod, new { @id = "PostResponseMethod" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 13 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
Write(Html.Hidden("PostFormId", Model.PostFormId, new { @id = "PostFormId" + randomKey }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Shared\_ModelFormViewCore.cshtml"
   Html.RenderPartial("AdminInputs/_PropertiesEdit", Model);
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
