#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/GeneralModelModal.cshtml")]
    public partial class _Areas_Admin_Views_Shared_GeneralModelModal_cshtml : System.Web.Mvc.WebViewPage<SDHC.Common.Entity.Models.ModelPostModel>
    {
        public _Areas_Admin_Views_Shared_GeneralModelModal_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
  
  var outID = Model.PostFormId;
  Model.PostFormId = "form_" + Model.PostFormId;

            
            #line default
            #line hidden
WriteLiteral("\r\n<script>\r\n  function formIdSubmit_");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                    Write(Model.PostFormId);

            
            #line default
            #line hidden
WriteLiteral("() {\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
     if (Model.IsPostAjax)
    {

            
            #line default
            #line hidden
WriteLiteral("      ");

WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
     if (!String.IsNullOrEmpty(Model.PostBeforeMethod))
    {

            
            #line default
            #line hidden
WriteLiteral("      ");

WriteLiteral("\r\n");

WriteLiteral("        ");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
    Write(Model.PostBeforeMethod);

            
            #line default
            #line hidden
WriteLiteral("(\'");

            
            #line 14 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                               Write(Model.PostFormId);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n      ");

WriteLiteral("\r\n");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    event.preventDefault();\r\n    var formData = new FormData(document.getElementB" +
"yId(\'");

            
            #line 18 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                                                    Write(Model.PostFormId);

            
            #line default
            #line hidden
WriteLiteral("\'));\r\n    $.ajax({\r\n      url: \'");

            
            #line 20 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
       Write(Model.PostUrl);

            
            #line default
            #line hidden
WriteLiteral("\',\r\n      type: \'post\',\r\n      data: formData,\r\n      contentType: false,\r\n      " +
"processData: false,\r\n    })\r\n      .then(function (response) {\r\n        var resp" +
"onseMethod = ");

            
            #line 27 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                         Write(string.IsNullOrEmpty(Model.PostResponseMethod) ?null: Model.PostResponseMethod);

            
            #line default
            #line hidden
WriteLiteral(";\r\n        if (responseMethod != null) {\r\n          responseMethod(response);\r\n  " +
"      }\r\n      });\r\n\r\n    $(\'#hide_");

            
            #line 33 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
        Write(Model.PostFormId);

            
            #line default
            #line hidden
WriteLiteral("\').click();\r\n    return false;\r\n      ");

WriteLiteral("\r\n");

            
            #line 36 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("  }\r\n</script>\r\n<div");

WriteLiteral(" class=\"modal fade\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1036), Tuple.Create("\"", 1047)
            
            #line 39 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
, Tuple.Create(Tuple.Create("", 1041), Tuple.Create<System.Object, System.Int32>(outID
            
            #line default
            #line hidden
, 1041), false)
);

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n  <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(">\r\n    <form");

WriteAttribute("id", Tuple.Create(" id=\"", 1156), Tuple.Create("\"", 1178)
            
            #line 41 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
, Tuple.Create(Tuple.Create("", 1161), Tuple.Create<System.Object, System.Int32>(Model.PostFormId
            
            #line default
            #line hidden
, 1161), false)
);

WriteAttribute("onsubmit", Tuple.Create(" onsubmit=\"", 1179), Tuple.Create("\"", 1224)
, Tuple.Create(Tuple.Create("", 1190), Tuple.Create("formIdSubmit_", 1190), true)
            
            #line 41 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
, Tuple.Create(Tuple.Create("", 1203), Tuple.Create<System.Object, System.Int32>(Model.PostFormId
            
            #line default
            #line hidden
, 1203), false)
, Tuple.Create(Tuple.Create("", 1222), Tuple.Create("()", 1222), true)
);

WriteLiteral(" enctype=\"multipart/form-data\"");

WriteAttribute("action", Tuple.Create(" action=\"", 1255), Tuple.Create("\"", 1278)
            
            #line 41 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                                     , Tuple.Create(Tuple.Create("", 1264), Tuple.Create<System.Object, System.Int32>(Model.PostUrl
            
            #line default
            #line hidden
, 1264), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(">\r\n          <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(" aria-label=\"Close\"");

WriteLiteral("><span");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">x</span></button>\r\n          <h4");

WriteLiteral(" class=\"modal-title\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1530), Tuple.Create("\"", 1549)
, Tuple.Create(Tuple.Create("", 1535), Tuple.Create("myModal_", 1535), true)
            
            #line 45 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
, Tuple.Create(Tuple.Create("", 1543), Tuple.Create<System.Object, System.Int32>(outID
            
            #line default
            #line hidden
, 1543), false)
);

WriteLiteral(">");

            
            #line 45 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
                                                 Write(Model.PostFormTitle);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
          
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
             Html.RenderPartial("_ModelFormViewCore", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n          <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success waves-effect waves-light m-r-10\"");

WriteLiteral(">Submit</button>\r\n        </div>\r\n        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" style=\"display:none\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1863), Tuple.Create("\"", 1890)
, Tuple.Create(Tuple.Create("", 1868), Tuple.Create("hide_", 1868), true)
            
            #line 51 "..\..\Areas\Admin\Views\Shared\GeneralModelModal.cshtml"
, Tuple.Create(Tuple.Create("", 1873), Tuple.Create<System.Object, System.Int32>(Model.PostFormId
            
            #line default
            #line hidden
, 1873), false)
);

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Close</button>\r\n        ");

WriteLiteral("\r\n      </div>\r\n    </form>\r\n  </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
