#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/ModelManagement/Index.cshtml")]
    public partial class _Areas_Admin_Views_ModelManagement_Index_cshtml : System.Web.Mvc.WebViewPage<ContentTableHtmlView>
    {
        public _Areas_Admin_Views_ModelManagement_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Areas\Admin\Views\ModelManagement\Index.cshtml"
  
  ViewBag.Title = "Model Management";
  Model.FirstRowAction = "Edit";
  Model.FirstRowController = "ModelManagement";
  Model.FirstRowArea = "Area";
  Model.FirstRowObject = b => new { @area = "Admin", @id = (b as ContentTableRowItem).Id, @type = ModelManager.GetMapperKey((b as ContentTableRowItem).ThisType.FullName) };

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row clearfix\"");

WriteLiteral(">\r\n  <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"button-box\"");

WriteLiteral(">\r\n\r\n          <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info btn-group\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n            Create\r\n          </button>\r\n        </div>\r\n\r\n      </div>\r\n\r\n   " +
"   <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\ModelManagement\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 23 "..\..\Areas\Admin\Views\ModelManagement\Index.cshtml"
           Html.RenderPartial("Contents/_ContentTableHtml", Model); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n  <script>\r\n            $(function () {\r\n                $(\'.basic-example\').Da" +
"taTable();\r\n            });\r\n  </script>\r\n  ");

WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
