#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    using SDHC.Common.Entity.Types;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/AdminInputs/_AdminInput.cshtml")]
    public partial class _Areas_Admin_Views_Shared_AdminInputs__AdminInput_cshtml : System.Web.Mvc.WebViewPage<ContentPropertyIndex>
    {

#line 24 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
public System.Web.WebPages.HelperResult requiredMark(bool required)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 25 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 
  if (required)
  {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, "*");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 29 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }


#line default
#line hidden
});

#line 30 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}
#line default
#line hidden

#line 31 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
public System.Web.WebPages.HelperResult requiredAttr(bool required)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 32 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 
  if (required)
  {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "    ");

WriteLiteralTo(__razor_helper_writer, "required");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 36 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }


#line default
#line hidden
});

#line 37 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}
#line default
#line hidden

        public _Areas_Admin_Views_Shared_AdminInputs__AdminInput_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  
  var randomIndex = Guid.NewGuid().ToString().Replace('-', '_');

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 189), Tuple.Create("\"", 250)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 194), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 194), false)
, Tuple.Create(Tuple.Create("", 208), Tuple.Create("_Properties[", 208), true)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 220), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 220), false)
, Tuple.Create(Tuple.Create("", 245), Tuple.Create("].Key", 245), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 251), Tuple.Create("\"", 299)
, Tuple.Create(Tuple.Create("", 258), Tuple.Create("Properties[", 258), true)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                      , Tuple.Create(Tuple.Create("", 269), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 269), false)
, Tuple.Create(Tuple.Create("", 294), Tuple.Create("].Key", 294), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 300), Tuple.Create("\"", 327)
            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 308), Tuple.Create<System.Object, System.Int32>(Model.Property.Key
            
            #line default
            #line hidden
, 308), false)
);

WriteLiteral(" />\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 353), Tuple.Create("\"", 420)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 358), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 358), false)
, Tuple.Create(Tuple.Create("", 372), Tuple.Create("_Properties[", 372), true)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 384), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 384), false)
, Tuple.Create(Tuple.Create("", 409), Tuple.Create("].ValueType", 409), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 421), Tuple.Create("\"", 475)
, Tuple.Create(Tuple.Create("", 428), Tuple.Create("Properties[", 428), true)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                            , Tuple.Create(Tuple.Create("", 439), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 439), false)
, Tuple.Create(Tuple.Create("", 464), Tuple.Create("].ValueType", 464), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 476), Tuple.Create("\"", 509)
            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                        , Tuple.Create(Tuple.Create("", 484), Tuple.Create<System.Object, System.Int32>(Model.Property.ValueType
            
            #line default
            #line hidden
, 484), false)
);

WriteLiteral(" />\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 535), Tuple.Create("\"", 603)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 540), false)
, Tuple.Create(Tuple.Create("", 554), Tuple.Create("_Properties[", 554), true)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 566), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 566), false)
, Tuple.Create(Tuple.Create("", 591), Tuple.Create("].EditorType", 591), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 604), Tuple.Create("\"", 659)
, Tuple.Create(Tuple.Create("", 611), Tuple.Create("Properties[", 611), true)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                             , Tuple.Create(Tuple.Create("", 622), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 622), false)
, Tuple.Create(Tuple.Create("", 647), Tuple.Create("].EditorType", 647), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 660), Tuple.Create("\"", 694)
            
            #line 9 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                          , Tuple.Create(Tuple.Create("", 668), Tuple.Create<System.Object, System.Int32>(Model.Property.EditorType
            
            #line default
            #line hidden
, 668), false)
);

WriteLiteral(" />\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("id", Tuple.Create(" id=\"", 720), Tuple.Create("\"", 789)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 725), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 725), false)
, Tuple.Create(Tuple.Create("", 739), Tuple.Create("_Properties[", 739), true)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 751), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 751), false)
, Tuple.Create(Tuple.Create("", 776), Tuple.Create("].MultiSelect", 776), true)
);

WriteAttribute("name", Tuple.Create(" name=\"", 790), Tuple.Create("\"", 846)
, Tuple.Create(Tuple.Create("", 797), Tuple.Create("Properties[", 797), true)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                              , Tuple.Create(Tuple.Create("", 808), Tuple.Create<System.Object, System.Int32>(Model.Index.ToString()
            
            #line default
            #line hidden
, 808), false)
, Tuple.Create(Tuple.Create("", 833), Tuple.Create("].MultiSelect", 833), true)
);

WriteAttribute("value", Tuple.Create(" value=\"", 847), Tuple.Create("\"", 882)
            
            #line 10 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                            , Tuple.Create(Tuple.Create("", 855), Tuple.Create<System.Object, System.Int32>(Model.Property.MultiSelect
            
            #line default
            #line hidden
, 855), false)
);

WriteLiteral(" />\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  
  var valueName = "Value";
  if (Model.Property.MultiSelect)
  {

    valueName = "MultiValue";

  }
  var inputName = "Properties[" + @Model.Index.ToString() + "]." + @valueName;
  var FileName = "Properties[" + @Model.Index.ToString() + "].File";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 if (Model.Property.NewLine)
{

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}

            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 if (Model.Property.Readonly)
{

            
            #line default
            #line hidden
WriteLiteral("  <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 1446), Tuple.Create("\"", 1463)
            
            #line 44 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 1453), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 1453), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1464), Tuple.Create("\"", 1493)
            
            #line 44 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 1472), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 1472), false)
);

WriteLiteral(" />\r\n");

            
            #line 45 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1527), Tuple.Create("\"", 1629)
            
            #line 47 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 1535), Tuple.Create<System.Object, System.Int32>(Model.Property.InputWidth>0?"width:"+Model.Property.InputWidth+"%;display:inline-block;":""
            
            #line default
            #line hidden
, 1535), false)
);

WriteLiteral(">\r\n  <label>\r\n");

WriteLiteral("    ");

            
            #line 49 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(Model.Property.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 50 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    
            
            #line default
            #line hidden
            
            #line 50 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
     if (Model.Property.EditorType == EnumInputType.Range)
    {

            
            #line default
            #line hidden
WriteLiteral("      <script>\r\n      function on_range_select_change_");

            
            #line 53 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                  Write(randomIndex);

            
            #line default
            #line hidden
WriteLiteral("(v) {\r\n        $(\'#range_value_");

            
            #line 54 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                   Write(randomIndex);

            
            #line default
            #line hidden
WriteLiteral("\').text(v.value);\r\n      }\r\n      </script>\r\n");

WriteLiteral("      <span");

WriteAttribute("id", Tuple.Create(" id=\"", 1905), Tuple.Create("\"", 1934)
, Tuple.Create(Tuple.Create("", 1910), Tuple.Create("range_value_", 1910), true)
            
            #line 57 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 1922), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 1922), false)
);

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 58 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\r\n      </span>\r\n");

            
            #line 60 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");

            
            #line 61 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(requiredMark(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral("\r\n  </label>\r\n");

            
            #line 63 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Text)
  {

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                  Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                    Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                       Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                               Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");

            
            #line 66 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 67 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Password)
  {

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" ");

            
            #line 69 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                      Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 69 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                        Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 69 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                           Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 69 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                   Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");

            
            #line 70 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 71 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.TextArea)
  {

            
            #line default
            #line hidden
WriteLiteral("    <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ");

            
            #line 73 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                              Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" rows=\"5\" name=\"");

            
            #line 73 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                    Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 73 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                 Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 73 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                               Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n");

            
            #line 74 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 75 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Number)
  {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"input-group spinner\"");

WriteLiteral(" data-trigger=\"spinner\"");

WriteLiteral(">\r\n      <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" data-spin=\"up\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"spin-up\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i></a>\r\n      </span>\r\n      <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-rule=\"quantity\"");

WriteLiteral(" data-min=\"");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                    Write(Model.Property.HasRangeMin?Model.Property.RangeMin.ToString():"null");

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-max=\"");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                       Write(Model.Property.HasRangeMax?Model.Property.RangeMax.ToString():"null");

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                               Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                 Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                                    Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                                                            Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/>\r\n      <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" data-spin=\"down\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"spin-down\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-minus\"");

WriteLiteral("></i></a>\r\n      </span>\r\n    </div>\r\n");

            
            #line 86 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 87 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Currency)
  {

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"input-group spinner\"");

WriteLiteral(" data-trigger=\"spinner\"");

WriteLiteral(">\r\n      <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" data-spin=\"up\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"spin-up\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-plus\"");

WriteLiteral("></i></a>\r\n      </span>\r\n      <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" data-rule=\"currency\"");

WriteLiteral(" data-min=\"");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                    Write(Model.Property.HasRangeMin?Model.Property.RangeMin.ToString():"null");

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-max=\"");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                       Write(Model.Property.HasRangeMax?Model.Property.RangeMax.ToString():"null");

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" ");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                               Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                 Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                                    Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                                                                                            Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/>\r\n      <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" data-spin=\"down\"");

WriteLiteral(">\r\n        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteLiteral(" class=\"spin-down\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-minus\"");

WriteLiteral("></i></a>\r\n      </span>\r\n    </div>\r\n");

            
            #line 98 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 99 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Range)
  {

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"range\"");

WriteAttribute("onchange", Tuple.Create(" onchange=\"", 4580), Tuple.Create("\"", 4634)
, Tuple.Create(Tuple.Create("", 4591), Tuple.Create("on_range_select_change_", 4591), true)
            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4614), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 4614), false)
, Tuple.Create(Tuple.Create("", 4628), Tuple.Create("(this)", 4628), true)
);

WriteAttribute("min", Tuple.Create(" min=\"", 4635), Tuple.Create("\"", 4665)
            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    , Tuple.Create(Tuple.Create("", 4641), Tuple.Create<System.Object, System.Int32>(Model.Property.RangeMin
            
            #line default
            #line hidden
, 4641), false)
);

WriteAttribute("max", Tuple.Create(" max=\"", 4666), Tuple.Create("\"", 4696)
            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                   , Tuple.Create(Tuple.Create("", 4672), Tuple.Create<System.Object, System.Int32>(Model.Property.RangeMax
            
            #line default
            #line hidden
, 4672), false)
);

WriteLiteral(" ");

            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                        Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                          Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                             Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 101 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                                                                                     Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/>\r\n");

            
            #line 102 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 103 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Html)
  {

            
            #line default
            #line hidden
WriteLiteral("    <textarea");

WriteAttribute("id", Tuple.Create(" id=\"", 4936), Tuple.Create("\"", 4977)
, Tuple.Create(Tuple.Create("", 4941), Tuple.Create("html_editor_", 4941), true)
            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4953), Tuple.Create<System.Object, System.Int32>(Model.Index
            
            #line default
            #line hidden
, 4953), false)
            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4965), Tuple.Create<System.Object, System.Int32>(randomIndex
            
            #line default
            #line hidden
, 4965), false)
);

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ");

            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                        Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" name=\"");

            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                     Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                  Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral(">");

            
            #line 105 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                                                                Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n");

            
            #line 106 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 107 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.Bool)
  {

            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 5216), Tuple.Create("\"", 5233)
            
            #line 109 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 5223), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 5223), false)
);

WriteLiteral(" ");

            
            #line 109 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                         Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 109 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                 Write(Model.Property.Readonly ? "disabled" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\">\r\n      <option ");

            
            #line 110 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
          Write(Model.Property.Value == "True" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"True\">Yes</option>\r\n      <option ");

            
            #line 111 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
          Write(Model.Property.Value == "False" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"False\">No</option>\r\n    </select>\r\n");

            
            #line 113 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 114 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.DateTime)
  {
    
            
            #line default
            #line hidden
            
            #line 121 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
              

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"input-group date form_datetime \"");

WriteLiteral(">\r\n      <span");

WriteLiteral(" class=\"input-group-addon bg\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n      <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ");

            
            #line 124 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                    Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" name=\"");

            
            #line 124 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                 Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 124 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                     Write(!String.IsNullOrEmpty(Model.Property.Value)?Model.Property.Value.Contains("T")? Model.Property.Value.Split('T').FirstOrDefault() : Model.Property.Value.Split(' ').FirstOrDefault() :"" );

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"yyyy-mm-dd\" readonly class=\"form-control\">\r\n\r\n    </div>\r\n");

            
            #line 127 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 128 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.DropDwon)
  {

            
            #line default
            #line hidden
WriteLiteral("    <select");

WriteAttribute("name", Tuple.Create(" name=\"", 6548), Tuple.Create("\"", 6565)
            
            #line 130 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 6555), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 6555), false)
);

WriteLiteral(" ");

            
            #line 130 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                         Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 130 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                 Write(Model.Property.Readonly ? "disabled" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" ");

            
            #line 130 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                   Write(Model.Property.MultiSelect ? "multiple" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n      <option>- -</option>\r\n");

            
            #line 132 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      
            
            #line default
            #line hidden
            
            #line 132 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       foreach (var item in Model.Property.SelectItems)
      {
        if (item.Select)
        {

            
            #line default
            #line hidden
WriteLiteral("          <option selected");

WriteAttribute("value", Tuple.Create(" value=\"", 6879), Tuple.Create("\"", 6900)
            
            #line 136 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 6887), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 6887), false)
);

WriteLiteral(">");

            
            #line 136 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                             Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 137 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("          <option");

WriteAttribute("value", Tuple.Create(" value=\"", 6978), Tuple.Create("\"", 6999)
            
            #line 140 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 6986), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 6986), false)
);

WriteLiteral(">");

            
            #line 140 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                    Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 141 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
        }

      }

            
            #line default
            #line hidden
WriteLiteral("    </select>\r\n");

            
            #line 145 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 146 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.FileUpload)
  {
    if (!string.IsNullOrEmpty(Model.Property.Value))
    {

            
            #line default
            #line hidden
WriteLiteral("      <p>\r\n        <img");

WriteLiteral(" style=\"display:block; max-width: 120px;max-height: 120px; margin-bottom: 10px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7298), Tuple.Create("\"", 7364)
            
            #line 151 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                  , Tuple.Create(Tuple.Create("", 7304), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 7304), false)
);

WriteLiteral(" />\r\n      </p>\r\n");

            
            #line 153 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" style=\"display:block\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" ");

            
            #line 155 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                        Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 155 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                          Write(FileName);

            
            #line default
            #line hidden
WriteLiteral("\" ");

            
            #line 155 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                      Write(Model.Property.Readonly ? "disabled" : null);

            
            #line default
            #line hidden
WriteLiteral("/> ");

WriteLiteral("<br />\r\n");

WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 7594), Tuple.Create("\"", 7611)
            
            #line 156 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 7601), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 7601), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 7612), Tuple.Create("\"", 7641)
            
            #line 156 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 7620), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 7620), false)
);

WriteLiteral(" />\r\n");

            
            #line 157 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("  ");

            
            #line 158 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
   if (Model.Property.EditorType == EnumInputType.OuterFile)
  {
    if (!string.IsNullOrEmpty(Model.Property.Value))
    {

            
            #line default
            #line hidden
WriteLiteral("      <p>\r\n        <img");

WriteLiteral(" style=\"display:block; max-width: 120px;max-height: 120px; margin-bottom: 10px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7883), Tuple.Create("\"", 7949)
            
            #line 163 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                  , Tuple.Create(Tuple.Create("", 7889), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 7889), false)
);

WriteLiteral(" />\r\n      </p>\r\n");

WriteLiteral("      <p>\r\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 7988), Tuple.Create("\"", 8055)
            
            #line 166 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 7995), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 7995), false)
);

WriteLiteral(" download>Download</a>\r\n      </p>\r\n");

            
            #line 168 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"

    }

            
            #line default
            #line hidden
WriteLiteral("    <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 8125), Tuple.Create("\"", 8142)
            
            #line 170 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 8132), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 8132), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 8143), Tuple.Create("\"", 8172)
            
            #line 170 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 8151), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 8151), false)
);

WriteLiteral(" />\r\n");

            
            #line 171 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 173 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 if (Model.Property.NewLineAfter)
{

            
            #line default
            #line hidden
WriteLiteral("  <br />\r\n");

            
            #line 176 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
