#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    using SDHC.Common.Entity.Types;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/AdminInputs/_AdminInput.cshtml")]
    public partial class _Areas_Admin_Views_Shared_AdminInputs__AdminInput_cshtml : System.Web.Mvc.WebViewPage<ContentPropertyIndex>
    {

#line 21 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
public System.Web.WebPages.HelperResult requiredMark(bool required)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 22 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 
    if (required)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, "*");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 26 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    }


#line default
#line hidden
});

#line 27 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}
#line default
#line hidden

#line 28 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
public System.Web.WebPages.HelperResult requiredAttr(bool required)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 29 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 
    if (required)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ");

WriteLiteralTo(__razor_helper_writer, "required");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 33 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
    }


#line default
#line hidden
});

#line 34 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}
#line default
#line hidden

        public _Areas_Admin_Views_Shared_AdminInputs__AdminInput_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].Key", Model.Property.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].ValueType", Model.Property.ValueType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].EditorType", Model.Property.EditorType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].MultiSelect", Model.Property.MultiSelect));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
  
    var valueName = "Value";
    if (Model.Property.MultiSelect)
    {

        valueName = "MultiValue";

    }
    var inputName = "Properties[" + @Model.Index.ToString() + "]." + @valueName;
    var FileName = "Properties[" + @Model.Index.ToString() + "].File";
    

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 35 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 if (Model.Property.NewLine)
{

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 38 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1045), Tuple.Create("\"", 1147)
            
            #line 39 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 1053), Tuple.Create<System.Object, System.Int32>(Model.Property.InputWidth>0?"width:"+Model.Property.InputWidth+"%;display:inline-block;":""
            
            #line default
            #line hidden
, 1053), false)
);

WriteLiteral(">\r\n      <label>");

            
            #line 40 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
        Write(Model.Property.Title);

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 40 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                              Write(requiredMark(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      
            
            #line default
            #line hidden
            
            #line 41 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.Text)
      {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ");

            
            #line 43 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                      Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 43 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                        Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 43 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                           Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

            
            #line 44 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 45 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.Password)
      {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" ");

            
            #line 47 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                          Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 47 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                            Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 47 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                               Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 49 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.TextArea)
      {

            
            #line default
            #line hidden
WriteLiteral("        <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                  Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" rows=\"5\" name=\"");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                        Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\">");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                    Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n");

            
            #line 52 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 53 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.Number)
      {

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" ");

            
            #line 55 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                        Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 55 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                          Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 55 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                             Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 57 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.Html)
      {

            
            #line default
            #line hidden
WriteLiteral("        <textarea");

WriteAttribute("id", Tuple.Create(" id=\"", 2209), Tuple.Create("\"", 2238)
, Tuple.Create(Tuple.Create("", 2214), Tuple.Create("html_editor_", 2214), true)
            
            #line 59 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 2226), Tuple.Create<System.Object, System.Int32>(Model.Index
            
            #line default
            #line hidden
, 2226), false)
);

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" name=\"");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                             Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\">");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                         Write(Model.Property.Value);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n");

            
            #line 60 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 61 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.Bool)
      {

            
            #line default
            #line hidden
WriteLiteral("        <select");

WriteAttribute("name", Tuple.Create(" name=\"", 2446), Tuple.Create("\"", 2463)
            
            #line 63 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 2453), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 2453), false)
);

WriteLiteral(" ");

            
            #line 63 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                             Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 63 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                     Write(Model.Property.Readonly ? "disabled" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\">\r\n          <option ");

            
            #line 64 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
              Write(Model.Property.Value == "True" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"True\">Yes</option>\r\n          <option ");

            
            #line 65 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
              Write(Model.Property.Value == "False" ? "selected" : "");

            
            #line default
            #line hidden
WriteLiteral(" value=\"False\">No</option>\r\n        </select>\r\n");

            
            #line 67 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 68 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.DateTime)
      {
        
            
            #line default
            #line hidden
            
            #line 75 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
              

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"input-group date form_datetime \"");

WriteLiteral(">\r\n          <span");

WriteLiteral(" class=\"input-group-addon bg\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n          <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ");

            
            #line 78 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                        Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" name=\"");

            
            #line 78 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                     Write(inputName);

            
            #line default
            #line hidden
WriteLiteral("\" value=\"");

            
            #line 78 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                         Write(!String.IsNullOrEmpty(Model.Property.Value)?Model.Property.Value.Contains("T")? Model.Property.Value.Split('T').FirstOrDefault() : Model.Property.Value.Split(' ').FirstOrDefault() :"" );

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"yyyy-mm-dd\" readonly class=\"form-control\">\r\n\r\n        </div>\r\n");

            
            #line 81 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 82 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.DropDwon)
      {

            
            #line default
            #line hidden
WriteLiteral("        <select");

WriteAttribute("name", Tuple.Create(" name=\"", 3838), Tuple.Create("\"", 3855)
            
            #line 84 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 3845), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 3845), false)
);

WriteLiteral(" ");

            
            #line 84 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                             Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" ");

            
            #line 84 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                     Write(Model.Property.Readonly ? "disabled" : "");

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" ");

            
            #line 84 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                                                       Write(Model.Property.MultiSelect ? "multiple" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");

            
            #line 85 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
          
            
            #line default
            #line hidden
            
            #line 85 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
           foreach (var item in Model.Property.SelectItems)
          {
            if (item.Select)
            {

            
            #line default
            #line hidden
WriteLiteral("              <option selected");

WriteAttribute("value", Tuple.Create(" value=\"", 4161), Tuple.Create("\"", 4182)
            
            #line 89 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4169), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 4169), false)
);

WriteLiteral(">");

            
            #line 89 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                 Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 90 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
            }
            else
            {

            
            #line default
            #line hidden
WriteLiteral("              <option");

WriteAttribute("value", Tuple.Create(" value=\"", 4276), Tuple.Create("\"", 4297)
            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4284), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 4284), false)
);

WriteLiteral(">");

            
            #line 93 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                        Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");

            
            #line 94 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
            }

          }

            
            #line default
            #line hidden
WriteLiteral("        </select>\r\n");

            
            #line 98 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 99 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.FileUpload)
      {
        if (!string.IsNullOrEmpty(Model.Property.Value))
        {

            
            #line default
            #line hidden
WriteLiteral("          <p>\r\n            <img");

WriteLiteral(" style=\"display:block; max-width: 120px;max-height: 120px; margin-bottom: 10px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4636), Tuple.Create("\"", 4702)
            
            #line 104 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                      , Tuple.Create(Tuple.Create("", 4642), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 4642), false)
);

WriteLiteral(" />\r\n          </p>\r\n");

            
            #line 106 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" style=\"display:block\"");

WriteLiteral(" type=\"file\"");

WriteLiteral(" ");

            
            #line 108 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                            Write(requiredAttr(Model.Property.Required));

            
            #line default
            #line hidden
WriteLiteral(" class=\"form-control\" name=\"");

            
            #line 108 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                                                                                                              Write(FileName);

            
            #line default
            #line hidden
WriteLiteral("\" /> ");

WriteLiteral("<br />\r\n");

WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 4902), Tuple.Create("\"", 4919)
            
            #line 109 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4909), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 4909), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 4920), Tuple.Create("\"", 4949)
            
            #line 109 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 4928), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 4928), false)
);

WriteLiteral(" />\r\n");

            
            #line 110 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      ");

            
            #line 111 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
       if (Model.Property.EditorType == EnumInputType.OuterFile)
      {
        if (!string.IsNullOrEmpty(Model.Property.Value))
        {

            
            #line default
            #line hidden
WriteLiteral("          <p>\r\n            <img");

WriteLiteral(" style=\"display:block; max-width: 120px;max-height: 120px; margin-bottom: 10px;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5219), Tuple.Create("\"", 5285)
            
            #line 116 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
                      , Tuple.Create(Tuple.Create("", 5225), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 5225), false)
);

WriteLiteral(" />\r\n          </p>\r\n");

WriteLiteral("          <p>\r\n            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 5336), Tuple.Create("\"", 5403)
            
            #line 119 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 5343), Tuple.Create<System.Object, System.Int32>(ContentExtends.GetUrlPath(Model.Property.Value.ImagePath())
            
            #line default
            #line hidden
, 5343), false)
);

WriteLiteral(" download >Download</a>\r\n          </p>\r\n");

            
            #line 121 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"

        }

            
            #line default
            #line hidden
WriteLiteral("        <input");

WriteLiteral(" type=\"hidden\"");

WriteAttribute("name", Tuple.Create(" name=\"", 5486), Tuple.Create("\"", 5503)
            
            #line 123 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 5493), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 5493), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 5504), Tuple.Create("\"", 5533)
            
            #line 123 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
, Tuple.Create(Tuple.Create("", 5512), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 5512), false)
);

WriteLiteral(" />\r\n");

            
            #line 124 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");

            
            #line 126 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
 if (Model.Property.NewLineAfter)
{

            
            #line default
            #line hidden
WriteLiteral("    <br />\r\n");

            
            #line 129 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
