#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
    using SDHC.Common.Entity.Types;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/AdminInputs/_AdminInput_Ignore.cshtml")]
    public partial class _Areas_Admin_Views_Shared_AdminInputs__AdminInput_Ignore_cshtml : System.Web.Mvc.WebViewPage<ContentPropertyIndex>
    {
        public _Areas_Admin_Views_Shared_AdminInputs__AdminInput_Ignore_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].Key", Model.Property.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 5 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].ValueType", Model.Property.ValueType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].EditorType", Model.Property.EditorType));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
Write(Html.Hidden("Properties[" + Model.Index.ToString() + "].MultiSelect", Model.Property.MultiSelect));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
  
    var valueName = "Value";
    if (Model.Property.MultiSelect)
    {

        valueName = "MultiValue";

    }
    var inputName = "Properties[" + @Model.Index.ToString() + "]." + @valueName;
    var FileName = "Properties[" + @Model.Index.ToString() + "].File";

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral("  class=\"form-control\"");

WriteAttribute("name", Tuple.Create(" name=\"", 797), Tuple.Create("\"", 814)
            
            #line 19 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
, Tuple.Create(Tuple.Create("", 804), Tuple.Create<System.Object, System.Int32>(inputName
            
            #line default
            #line hidden
, 804), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 815), Tuple.Create("\"", 844)
            
            #line 19 "..\..\Areas\Admin\Views\Shared\AdminInputs\_AdminInput_Ignore.cshtml"
, Tuple.Create(Tuple.Create("", 823), Tuple.Create<System.Object, System.Int32>(Model.Property.Value
            
            #line default
            #line hidden
, 823), false)
);

WriteLiteral(" />");

        }
    }
}
#pragma warning restore 1591
