#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    
    #line 1 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Content/_CreateOrEdit.cshtml")]
    public partial class _Areas_Admin_Views_Content__CreateOrEdit_cshtml : System.Web.Mvc.WebViewPage<ContentPostModel>
    {
        public _Areas_Admin_Views_Content__CreateOrEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
   
  var a = Model;
  var v = Model.Id;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
Write(Html.Hidden("Id", Model.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 8 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
Write(Html.Hidden("ParentId", Model.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"FullType\"");

WriteLiteral(" id=\"FullType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 228), Tuple.Create("\"", 251)
            
            #line 9 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 236), Tuple.Create<System.Object, System.Int32>(Model.FullType
            
            #line default
            #line hidden
, 236), false)
);

WriteLiteral(" />\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
Write(Html.Hidden("ThisAssembly", Model.ThisAssembly));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
Write(Html.Hidden("CreateTime", Model.CreateTime));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 12 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
Write(Html.Hidden("DisplayOrder", Model.DisplayOrder));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label>Title</label>\r\n    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"Title\"");

WriteAttribute("value", Tuple.Create(" value=\"", 513), Tuple.Create("\"", 533)
            
            #line 16 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
, Tuple.Create(Tuple.Create("", 521), Tuple.Create<System.Object, System.Int32>(Model.Title
            
            #line default
            #line hidden
, 521), false)
);

WriteLiteral(" required />\r\n</div>\r\n\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Content\_CreateOrEdit.cshtml"
   Html.RenderPartial("AdminInputs/_PropertiesEdit", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n<button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success waves-effect waves-light m-r-10\"");

WriteLiteral(">Submit</button>\r\n");

        }
    }
}
#pragma warning restore 1591
