#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Content\Index.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Content/Index.cshtml")]
    public partial class _Areas_Admin_Views_Content_Index_cshtml : System.Web.Mvc.WebViewPage<BaseContent>
    {
        public _Areas_Admin_Views_Content_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Content\Index.cshtml"
  
  ViewBag.Title = "Content";
  Layout = "~/Areas/Admin/Views/Shared/_Layout_Content.cshtml";
  var contentId = Model != null ? (long?)Model.Id : null;
  var contents = ContentManager.GetContentTableHtmlView(contentId);
  contents.FirstRow = new ContentTableOption()
  {
    RowAction = "Index",
    RowController = "Content",
    RowArea = G.AdminPath,
    RowTitle = b => $"{(b as ContentTableRowItem).DisplayOrder} (children list)",
    RowObject = b => new { @id = (b as ContentTableRowItem).Id, @area = G.AdminPath }
  };
  contents.Options = new List<ContentTableOption>();
  contents.Options.Add(
    new ContentTableOption()
    {
      RowAction = "Edit",
      RowController = "Content",
      RowArea = G.AdminPath,
      RowTitle = b => "Detail",
      ButtonClass = "btn btn-primary",
      RowObject = b => new { @id = (b as ContentTableRowItem).Id, @area = G.AdminPath }
    });
  contents.Options.Add(
    new ContentTableOption()
    {
      RowAction = "Preview",
      RowController = "SDHCPage",
      RowArea = "",
      RowTitle = b => "Preview",
      ButtonClass = "btn btn-success",
      RowObject = b => new { @id = (b as ContentTableRowItem).Id, @area = "" },
      UrlAttribute = c => $"target=\"_blank\"",
    });

 

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("breadcrumb", () => {

WriteLiteral("\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\Content\Index.cshtml"
  
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Admin\Views\Content\Index.cshtml"
     Html.RenderPartial("_BreadCrumbContent", Model);
            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("<script>\r\n  function subbform(id) {\r\n    var form = document.getElementById(id);\r" +
"\n    form.submit();\r\n    return;\r\n  }\r\n</script>\r\n<div");

WriteLiteral(" class=\"row clearfix\"");

WriteLiteral(">\r\n  <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"button-box\"");

WriteLiteral(">\r\n");

            
            #line 57 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          
            
            #line default
            #line hidden
            
            #line 57 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           if (ViewBag.IsInCreateRoles)
          {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"btn-group\"");

WriteLiteral(">\r\n              <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info btn-group\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                Create\r\n              </button>\r\n              <ul");

WriteLiteral(" class=\"dropdown-menu\"");

WriteLiteral(">\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                  
                  var avaliableChild = TypeExtends.GetAllowChildrens(Model);
                
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 67 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 67 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                 foreach (var child in avaliableChild)
                {
                  var idguid = Guid.NewGuid().ToString();

            
            #line default
            #line hidden
WriteLiteral("                  <li>\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 2356), Tuple.Create("\"", 2385)
, Tuple.Create(Tuple.Create("", 2366), Tuple.Create("subbform(\'", 2366), true)
            
            #line 71 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2376), Tuple.Create<System.Object, System.Int32>(idguid
            
            #line default
            #line hidden
, 2376), false)
, Tuple.Create(Tuple.Create("", 2383), Tuple.Create("\')", 2383), true)
);

WriteLiteral(">");

            
            #line 71 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                                                         Write(TypeExtends.GetClassDisplayName(child));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    <form");

WriteAttribute("id", Tuple.Create(" id=\"", 2457), Tuple.Create("\"", 2469)
            
            #line 72 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2462), Tuple.Create<System.Object, System.Int32>(idguid
            
            #line default
            #line hidden
, 2462), false)
);

WriteAttribute("action", Tuple.Create(" action=\"", 2470), Tuple.Create("\"", 2543)
            
            #line 72 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2479), Tuple.Create<System.Object, System.Int32>(Url.Action("PreCreate", "Content", new { @area = G.AdminPath })
            
            #line default
            #line hidden
, 2479), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("                      ");

            
            #line 73 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                 Write(Html.Hidden("ContentId", contentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                      ");

            
            #line 74 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                 Write(Html.Hidden("FullType", child.FullName + "," + child.Assembly.FullName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </form>\r\n                  </li>\r\n");

            
            #line 77 "..\..\Areas\Admin\Views\Content\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("              </ul>\r\n            </div>\r\n");

            
            #line 80 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("          ");

            
            #line 81 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           if (ViewBag.IsInEditRoles)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2910), Tuple.Create("\"", 2994)
            
            #line 83 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 2917), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Content", new { @area = G.AdminPath, @id = contentId })
            
            #line default
            #line hidden
, 2917), false)
);

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">List</a>\r\n");

            
            #line 84 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("          ");

            
            #line 85 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           if (ViewBag.IsInEditRoles)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3109), Tuple.Create("\"", 3192)
            
            #line 87 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3116), Tuple.Create<System.Object, System.Int32>(Url.Action("Edit", "Content", new { @area = G.AdminPath, @id = contentId })
            
            #line default
            #line hidden
, 3116), false)
);

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(">Edit</a>\r\n");

            
            #line 88 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("          ");

            
            #line 89 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           if (ViewBag.IsInSortRoles)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3307), Tuple.Create("\"", 3390)
            
            #line 91 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3314), Tuple.Create<System.Object, System.Int32>(Url.Action("Sort", "Content", new { @area = G.AdminPath, @id = contentId })
            
            #line default
            #line hidden
, 3314), false)
);

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(">Sort</a>\r\n");

            
            #line 92 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("          ");

            
            #line 93 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           if (ViewBag.IsInDeleteRoles)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" onclick=\"deleteCurrent()\"");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(">Delete</a>\r\n");

WriteLiteral("            <form");

WriteLiteral(" id=\"ContentDeleteForm\"");

WriteAttribute("action", Tuple.Create(" action=\"", 3618), Tuple.Create("\"", 3688)
            
            #line 96 "..\..\Areas\Admin\Views\Content\Index.cshtml"
, Tuple.Create(Tuple.Create("", 3627), Tuple.Create<System.Object, System.Int32>(Url.Action("Delete", "Content", new { @area = G.AdminPath })
            
            #line default
            #line hidden
, 3627), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

WriteLiteral("              ");

            
            #line 97 "..\..\Areas\Admin\Views\Content\Index.cshtml"
         Write(Html.Hidden("id", contentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </form>\r\n");

            
            #line 99 "..\..\Areas\Admin\Views\Content\Index.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n      </div>\r\n\r\n      <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n");

            
            #line 106 "..\..\Areas\Admin\Views\Content\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 106 "..\..\Areas\Admin\Views\Content\Index.cshtml"
           Html.RenderPartial("Contents/_ContentTableHtml", contents); 
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n");

DefineSection("script", () => {

WriteLiteral(@"
  <script>
    $(function () {
      $('.basic-example').DataTable();
    });

    function deleteCurrent() {
      showCancelMessage(function () {
        document.getElementById('ContentDeleteForm').submit();
      })
    }
    function showCancelMessage(callback) {
      swal({
        title: ""Are you sure?"",
        text: ""Current page and all Children page will delete and not be able to recover!"",
        type: ""warning"",
        showCancelButton: true,
        confirmButtonColor: ""#DD6B55"",
        confirmButtonText: ""Yes, delete it!"",
        cancelButtonText: ""No, cancel plx!"",
        closeOnConfirm: false,
        closeOnCancel: false
      }, function (isConfirm) {
        if (isConfirm) {
          swal(""Deleted!"", ""Your record has been deleted."", ""success"");
          if (callback) {
            callback();
          }
        } else {
          swal(""Cancelled"", ""Your record is safe :)"", ""error"");
        }
      });
    }
  </script>
  ");

WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
