#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
    using SDHC.Common.Entity.Models.ViewModels;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Content/Sort.cshtml")]
    public partial class _Areas_Admin_Views_Content_Sort_cshtml : System.Web.Mvc.WebViewPage<ContentListView>
    {

#line 7 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
public System.Web.WebPages.HelperResult RenderItem(ContentListView m)
{
#line default
#line hidden
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {

#line 8 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
 


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "  <li");

WriteAttributeTo(__razor_helper_writer, "id", Tuple.Create(" id=\"", 223), Tuple.Create("\"", 233)

#line 9 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
, Tuple.Create(Tuple.Create("", 228), Tuple.Create<System.Object, System.Int32>(m.Id

#line default
#line hidden
, 228), false)
);

WriteLiteralTo(__razor_helper_writer, ">\r\n");

WriteLiteralTo(__razor_helper_writer, "    ");


#line 10 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
WriteTo(__razor_helper_writer, String.IsNullOrEmpty(m.Title) ? "Root" : m.Title);


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 11 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
    

#line default
#line hidden

#line 11 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
     if (m.Children.Count > 0)
    {


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "      <ul>\r\n        ---\r\n");


#line 15 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
        

#line default
#line hidden

#line 15 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
         foreach (var item in m.Children)
        {



#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "          ");

WriteLiteralTo(__razor_helper_writer, "\r\n");

WriteLiteralTo(__razor_helper_writer, "            ");


#line 19 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
WriteTo(__razor_helper_writer, RenderItem(item));


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "\r\n          ");

WriteLiteralTo(__razor_helper_writer, "\r\n");


#line 21 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
        }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "        ---\r\n      </ul>\r\n");


#line 24 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
    }


#line default
#line hidden
WriteLiteralTo(__razor_helper_writer, "  </li>\r\n");


#line 26 "..\..\Areas\Admin\Views\Content\Sort.cshtml"


#line default
#line hidden
});

#line 26 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
}
#line default
#line hidden

        public _Areas_Admin_Views_Content_Sort_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
  
  ViewBag.Title = "Sort Content";
  Layout = "~/Areas/Admin/Views/Shared/_Layout_Content.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"row clearfix\"");

WriteLiteral(">\r\n  <div");

WriteLiteral(" class=\"col-lg-12 col-md-12 col-sm-12 col-xs-12\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n      <div");

WriteLiteral(" class=\"body\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n          <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"jstree_demo_div\"");

WriteLiteral(">\r\n              <ul>\r\n");

WriteLiteral("                ");

            
            #line 36 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
           Write(RenderItem(Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n              </ul>\r\n            </div>\r\n            <br />\r\n            <br />" +
"\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" onclick=\"submitList()\"");

WriteLiteral(" value=\"Save\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" onclick=\"goToList()\"");

WriteLiteral(" value=\"List\"");

WriteLiteral(" />\r\n            <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" name=\"name\"");

WriteLiteral(" onclick=\"goToEdit()\"");

WriteLiteral(" value=\"Edit\"");

WriteLiteral(" />\r\n          </div>\r\n        </div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n</div>" +
"\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n  <script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/jstree/3.3.7/jstree.min.js\"");

WriteLiteral(@"></script>
  <script>

        function pushSortItem(item,lists,parentId,displayOrder){
            lists.push({
                id:item.id,
                parentId:parentId,
                displayOrder:displayOrder,
            });
            if(item.children && item.children.length>0){
                for(var index = 0;index<item.children.length;index++){
                    pushSortItem(item.children[index],lists,item.id,index);
                }
            }
    }
    function getSelectNode(){
      var selectId = $('#jstree_demo_div').jstree(true).get_selected();
      if (selectId == null || selectId.length <= 0) {
        return """";
      }
      return selectId[0];
    }
    function goToList() {
      var url = """);

            
            #line 75 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
            Write(Url.Action("Index","Content",new { @id="[id]",@area=G.AdminPath }));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n      console.log(url);\r\n      window.location.href = url.replace(\"[id]\", get" +
"SelectNode());\r\n    }\r\n    function goToEdit() {\r\n      var url = \"");

            
            #line 80 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
            Write(Url.Action("Edit","Content",new { @id="[id]",@area=G.AdminPath }));

            
            #line default
            #line hidden
WriteLiteral(@""";
      console.log(url);
      window.location.href = url.replace(""[id]"", getSelectNode());
    }

    function submitList() {
            var data2 = $(""#jstree_demo_div"").jstree().get_json();
            var itemList = [];
            pushSortItem(data2[0],itemList,0,null);
            console.log(itemList);
            $.ajax({
                method: ""POST"",
                url: """);

            
            #line 92 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
                 Write(Url.Action("Sort","Content",new {@area=G.AdminPath} ));

            
            #line default
            #line hidden
WriteLiteral("\",\r\n                data: JSON.stringify(itemList),\r\n                contentType:" +
" \"application/json; charset=utf-8\",\r\n            }).done(function () {\r\n        " +
"      window.location.replace(\'");

            
            #line 96 "..\..\Areas\Admin\Views\Content\Sort.cshtml"
                                  Write(Url.Action("Index", "Content", new { @id=Model.Id, area = G.AdminPath }));

            
            #line default
            #line hidden
WriteLiteral(@"');
            });
        }

        $(function () {
            $('#jstree_demo_div').jstree({
                ""core"": {
                    ""animation"": 0,
                    ""check_callback"": true,
                    ""themes"": { ""stripes"": true },
                },
                ""types"": {
                    ""#"": {
                        ""max_children"": 1,
                        ""max_depth"": 9,
                        ""valid_children"": [""root""]
                    },
                    ""root"": {
                        ""icon"": ""/static/3.3.7/assets/images/tree_icon.png"",
                        ""valid_children"": [""default""]
                    },
                    ""default"": {
                        ""valid_children"": [""default"", ""file""]
                    },
                    ""file"": {
                        ""icon"": ""glyphicon glyphicon-file"",
                        ""valid_children"": []
                    }
                },
                ""plugins"": [
                    ""dnd"", ""search"",
                    ""state"", ""types"", ""wholerow""
                ]



            });
        });
  </script>
");

});

        }
    }
}
#pragma warning restore 1591
