#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/Contents/_ContentTableHtml.cshtml")]
    public partial class _Areas_Admin_Views_Shared_Contents__ContentTableHtml_cshtml : System.Web.Mvc.WebViewPage<ContentTableHtmlView>
    {
        public _Areas_Admin_Views_Shared_Contents__ContentTableHtml_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table");

WriteLiteral(" class=\"table table-bordered table-striped table-hover basic-example dataTable\"");

WriteLiteral(">\r\n  <thead>\r\n    <tr>\r\n      <th>Id</th>\r\n");

            
            #line 7 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
      
            
            #line default
            #line hidden
            
            #line 7 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
       foreach (var item in Model.TableHeaders)
      {

            
            #line default
            #line hidden
WriteLiteral("        <th>");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
       Write(item);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 10 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      <th>\r\n        Option\r\n      </th>\r\n\r\n    </tr>\r\n  </thead>\r\n  <tfoot>\r\n    " +
"<tr>\r\n      <th>Id</th>\r\n");

            
            #line 20 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
      
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
       foreach (var item in Model.TableHeaders)
      {

            
            #line default
            #line hidden
WriteLiteral("        <th>");

            
            #line 22 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
       Write(item);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n");

            
            #line 23 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
      }

            
            #line default
            #line hidden
WriteLiteral("      <th>\r\n        Option\r\n      </th>\r\n    </tr>\r\n  </tfoot>\r\n  <tbody>\r\n");

            
            #line 30 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
     foreach (var row in Model.Rows)
    {

            
            #line default
            #line hidden
WriteLiteral("      <tr>\r\n        <td>\r\n");

            
            #line 34 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          
            
            #line default
            #line hidden
            
            #line 34 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
           if (Model.FirstRow == null)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 660), Tuple.Create("\"", 751)
            
            #line 36 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 667), Tuple.Create<System.Object, System.Int32>(Url.Action(Model.FirstRowAction,Model.FirstRowController,Model.FirstRowObject(row))
            
            #line default
            #line hidden
, 667), false)
);

WriteLiteral(">");

            
            #line 36 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
                                                                                                      Write(row.Id);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 37 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          }
          else
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("class", Tuple.Create(" class=\"", 822), Tuple.Create("\"", 857)
            
            #line 40 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 830), Tuple.Create<System.Object, System.Int32>(Model.FirstRow.ButtonClass
            
            #line default
            #line hidden
, 830), false)
);

WriteAttribute("href", Tuple.Create(" href=\"", 858), Tuple.Create("\"", 961)
            
            #line 40 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 865), Tuple.Create<System.Object, System.Int32>(Url.Action(Model.FirstRow.RowAction,Model.FirstRow.RowController,Model.FirstRow.RowObject(row))
            
            #line default
            #line hidden
, 865), false)
);

WriteLiteral(">");

            
            #line 40 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
                                                                                                                                                      Write(Model.FirstRow.RowTitle(row));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 41 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n");

            
            #line 43 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
        
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
         foreach (var item in row.Values)
        {

            
            #line default
            #line hidden
WriteLiteral("          <td>");

            
            #line 45 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
         Write(item);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <td>\r\n");

            
            #line 48 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          
            
            #line default
            #line hidden
            
            #line 48 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
           if (Model.Options == null)
          {

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1197), Tuple.Create("\"", 1288)
            
            #line 50 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 1204), Tuple.Create<System.Object, System.Int32>(Url.Action(Model.FirstRowAction,Model.FirstRowController,Model.FirstRowObject(row))
            
            #line default
            #line hidden
, 1204), false)
);

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">Info</a>\r\n");

            
            #line 51 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          }
          else
          {
            foreach (var option in Model.Options)
            {

            
            #line default
            #line hidden
WriteLiteral("              <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1448), Tuple.Create("\"", 1528)
            
            #line 56 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 1455), Tuple.Create<System.Object, System.Int32>(Url.Action(option.RowAction,option.RowController, option.RowObject(row))
            
            #line default
            #line hidden
, 1455), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 1529), Tuple.Create("\"", 1556)
            
            #line 56 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
                         , Tuple.Create(Tuple.Create("", 1537), Tuple.Create<System.Object, System.Int32>(option.ButtonClass
            
            #line default
            #line hidden
, 1537), false)
);

WriteLiteral(">");

            
            #line 56 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
                                                                                                                         Write(option.RowTitle(row));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 57 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
            }
          }

            
            #line default
            #line hidden
WriteLiteral("          ");

            
            #line 59 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
           if (ViewBag.delete != null && !Model.DisableDelete)
          {

            
            #line default
            #line hidden
WriteLiteral("            <button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1732), Tuple.Create("\"", 1816)
            
            #line 61 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
, Tuple.Create(Tuple.Create("", 1742), Tuple.Create<System.Object, System.Int32>(ViewBag.deleteFunction!=null?ViewBag.deleteFunction+"("+ row.Id +")":""
            
            #line default
            #line hidden
, 1742), false)
);

WriteLiteral(">Delete</button>\r\n");

            
            #line 62 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
          }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n\r\n      </tr>\r\n");

            
            #line 66 "..\..\Areas\Admin\Views\Shared\Contents\_ContentTableHtml.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("  </tbody>\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
