#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_css.cshtml")]
    public partial class _Areas_Admin_Views_Shared__css_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__css_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!--REQUIRED PLUGIN CSS-->\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 33), Tuple.Create("\"", 97)
, Tuple.Create(Tuple.Create("", 40), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/font-awesome/css/font-awesome.min.css")
, 40), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 123), Tuple.Create("\"", 177)
, Tuple.Create(Tuple.Create("", 130), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap/css/bootstrap.css")
, 130), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 203), Tuple.Create("\"", 250)
, Tuple.Create(Tuple.Create("", 210), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/node-waves/waves.css")
, 210), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 278), Tuple.Create("\"", 328)
, Tuple.Create(Tuple.Create("", 285), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/animate-css/animate.css")
, 285), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 356), Tuple.Create("\"", 402)
, Tuple.Create(Tuple.Create("", 363), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/spinkit/spinkit.css")
, 363), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 430), Tuple.Create("\"", 532)
, Tuple.Create(Tuple.Create("", 437), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-date" +
"timepicker.css")
, 437), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 560), Tuple.Create("\"", 645)
, Tuple.Create(Tuple.Create("", 567), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-datetime-picker/css/bootstrap-datetimepicker.css")
, 567), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 673), Tuple.Create("\"", 751)
, Tuple.Create(Tuple.Create("", 680), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/boootstrap-datepicker/bootstrap-datepicker3.min.css")
, 680), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 779), Tuple.Create("\"", 855)
, Tuple.Create(Tuple.Create("", 786), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-timepicker/css/bootstrap-timepicker.css")
, 786), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 883), Tuple.Create("\"", 949)
, Tuple.Create(Tuple.Create("", 890), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/bootstrap-daterange/daterangepicker.css")
, 890), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 981), Tuple.Create("\"", 1068)
, Tuple.Create(Tuple.Create("", 988), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css")
, 988), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1094), Tuple.Create("\"", 1185)
, Tuple.Create(Tuple.Create("", 1101), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/skin/bootstrap/css/responsive.bootstrap.min." +
"css")
, 1101), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1211), Tuple.Create("\"", 1300)
, Tuple.Create(Tuple.Create("", 1218), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/skin/bootstrap/css/scroller.bootstrap.min.cs" +
"s")
, 1218), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1326), Tuple.Create("\"", 1418)
, Tuple.Create(Tuple.Create("", 1333), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/jquery-datatable/skin/bootstrap/css/fixedHeader.bootstrap.min" +
".css")
, 1333), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1444), Tuple.Create("\"", 1501)
, Tuple.Create(Tuple.Create("", 1451), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/footable/css/footable.core.css")
, 1451), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<!--REQUIRED THEME CSS -->\r\n\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1557), Tuple.Create("\"", 1596)
, Tuple.Create(Tuple.Create("", 1564), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/css/style.css")
, 1564), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1622), Tuple.Create("\"", 1662)
, Tuple.Create(Tuple.Create("", 1629), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/css/layout.css")
, 1629), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1688), Tuple.Create("\"", 1739)
, Tuple.Create(Tuple.Create("", 1695), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/assets/css/themes/main_theme.css")
, 1695), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1767), Tuple.Create("\"", 1819)
, Tuple.Create(Tuple.Create("", 1774), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/sweetalert/sweetalert.css")
, 1774), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<!--THIS PAGE LEVEL CSS-->\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1875), Tuple.Create("\"", 1921)
, Tuple.Create(Tuple.Create("", 1882), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/morrisjs/morris.css")
, 1882), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<!--Chat Css-->\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 1966), Tuple.Create("\"", 2025)
, Tuple.Create(Tuple.Create("", 1973), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/assets/css/style-light.css")
, 1973), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n<link");

WriteAttribute("href", Tuple.Create(" href=\"", 2051), Tuple.Create("\"", 2105)
, Tuple.Create(Tuple.Create("", 2058), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/assets/css/mobile.css")
, 2058), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" id=\"style\"");

WriteLiteral(">\r\n\r\n<!-- EMOJI ONE JS -->\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2184), Tuple.Create("\"", 2259)
, Tuple.Create(Tuple.Create("", 2191), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/smiley/assets/sprites/emojione.sprites.css")
, 2191), false)
);

WriteLiteral(" />\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 2272), Tuple.Create("\"", 2329)
, Tuple.Create(Tuple.Create("", 2278), Tuple.Create<System.Object, System.Int32>(Href("~/admin-lib/plugins/wchat/smiley/js/emojione.min.js")
, 2278), false)
);

WriteLiteral("></script>\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    // #################################################
    // # Optional

    // default is PNG but you may also use SVG
    emojione.imageType = 'png';
    emojione.sprites = false;

    // default is ignore ASCII smileys like :) but you can easily turn them on
    emojione.ascii = true;

    // if you want to host the images somewhere else
    // you can easily change the default paths
    emojione.imagePathPNG = '/admin-lib/plugins/wchat/smiley/assets/png/';
    emojione.imagePathSVG = '/admin-lib/plugins/wchat/smiley/assets/svg/';

        // #################################################
</script>
<!--#End# Chat Css-->
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src=""https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js""></script>
<script src=""https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js""></script>
<![endif]-->
");

        }
    }
}
#pragma warning restore 1591
