#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_Header.cshtml")]
    public partial class _Areas_Admin_Views_Shared__Header_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__Header_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<header");

WriteLiteral(" class=\"topbar\"");

WriteLiteral(">\r\n    <nav");

WriteLiteral(" class=\"navbar top-navbar navbar-toggleable-sm navbar-light\"");

WriteLiteral(">\r\n        <!-- ============================================================== --" +
">\r\n        <!-- Logo -->\r\n        <!-- =========================================" +
"===================== -->\r\n        <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n            <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"index.html\"");

WriteLiteral(">\r\n                <!-- Logo icon --><b>\r\n                    <!--You can put her" +
"e icon as well // <i class=\"wi wi-sunset\"></i> //-->\r\n                    <!-- D" +
"ark Logo icon -->\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 575), Tuple.Create("\"", 620)
, Tuple.Create(Tuple.Create("", 581), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/logo-icon.png")
, 581), false)
);

WriteLiteral(" alt=\"homepage\"");

WriteLiteral(" class=\"dark-logo\"");

WriteLiteral(" />\r\n                    <!-- Light Logo icon -->\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 729), Tuple.Create("\"", 780)
, Tuple.Create(Tuple.Create("", 735), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/logo-light-icon.png")
, 735), false)
);

WriteLiteral(" alt=\"homepage\"");

WriteLiteral(" class=\"light-logo\"");

WriteLiteral(" />\r\n                </b>\r\n                <!--End Logo icon -->\r\n               " +
" <!-- Logo text --><span>\r\n                    <!-- dark Logo text -->\r\n        " +
"            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 992), Tuple.Create("\"", 1037)
, Tuple.Create(Tuple.Create("", 998), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/logo-text.png")
, 998), false)
);

WriteLiteral(" alt=\"homepage\"");

WriteLiteral(" class=\"dark-logo\"");

WriteLiteral(" />\r\n                    <!-- Light Logo text -->\r\n                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1146), Tuple.Create("\"", 1197)
, Tuple.Create(Tuple.Create("", 1152), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/logo-light-text.png")
, 1152), false)
);

WriteLiteral(" class=\"light-logo\"");

WriteLiteral(" alt=\"homepage\"");

WriteLiteral(@" />
                </span>
            </a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div");

WriteLiteral(" class=\"navbar-collapse\"");

WriteLiteral(">\r\n            <!-- =============================================================" +
"= -->\r\n            <!-- toggle and nav items -->\r\n            <!-- =============" +
"================================================= -->\r\n            <ul");

WriteLiteral(" class=\"navbar-nav mr-auto mt-md-0 \"");

WriteLiteral(">\r\n                <!-- This is  -->\r\n                <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral("> <a");

WriteLiteral(" class=\"nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-menu\"");

WriteLiteral("></i></a> </li>\r\n                <li");

WriteLiteral(" class=\"nav-item\"");

WriteLiteral("> <a");

WriteLiteral(" class=\"nav-link sidebartoggler hidden-sm-down text-muted waves-effect waves-dark" +
"\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"icon-arrow-left-circle\"");

WriteLiteral("></i></a> </li>\r\n                <!-- ===========================================" +
"=================== -->\r\n                <!-- Comment -->\r\n                <!-- " +
"============================================================== -->\r\n            " +
"    <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle text-muted text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"mdi mdi-message\"");

WriteLiteral("></i>\r\n                        <div");

WriteLiteral(" class=\"notify\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"heartbit\"");

WriteLiteral("></span> <span");

WriteLiteral(" class=\"point\"");

WriteLiteral("></span> </div>\r\n                    </a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu mailbox animated bounceInDown\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li>\r\n              " +
"                  <div");

WriteLiteral(" class=\"drop-title\"");

WriteLiteral(">Notifications</div>\r\n                            </li>\r\n                        " +
"    <li>\r\n                                <div");

WriteLiteral(" class=\"message-center\"");

WriteLiteral(">\r\n                                    <!-- Message -->\r\n                        " +
"            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"btn btn-danger btn-circle\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-link\"");

WriteLiteral("></i></div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Luanch Admin</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">Just see the my new admin!</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:30 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"btn btn-success btn-circle\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-calendar\"");

WriteLiteral("></i></div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Event today</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">Just a reminder that you have event</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:10 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"btn btn-info btn-circle\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-settings\"");

WriteLiteral("></i></div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Settings</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">You can customize this template as you want</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:08 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"btn btn-primary btn-circle\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-user\"");

WriteLiteral("></i></div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Pavan kumar</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">Just see the my admin!</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:02 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                </div>\r\n              " +
"              </li>\r\n                            <li>\r\n                         " +
"       <a");

WriteLiteral(" class=\"nav-link text-center\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral("> <strong>Check all notifications</strong> <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral(@"></i> </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Comment -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"\"");

WriteLiteral(" id=\"2\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        <i");

WriteLiteral(" class=\"mdi mdi-email\"");

WriteLiteral("></i>\r\n                        <div");

WriteLiteral(" class=\"notify\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"heartbit\"");

WriteLiteral("></span> <span");

WriteLiteral(" class=\"point\"");

WriteLiteral("></span> </div>\r\n                    </a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu mailbox animated bounceInDown\"");

WriteLiteral(" aria-labelledby=\"2\"");

WriteLiteral(">\r\n                        <ul>\r\n                            <li>\r\n              " +
"                  <div");

WriteLiteral(" class=\"drop-title\"");

WriteLiteral(">You have 4 new messages</div>\r\n                            </li>\r\n              " +
"              <li>\r\n                                <div");

WriteLiteral(" class=\"message-center\"");

WriteLiteral(">\r\n                                    <!-- Message -->\r\n                        " +
"            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"user-img\"");

WriteLiteral("> <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7134), Tuple.Create("\"", 7177)
, Tuple.Create(Tuple.Create("", 7140), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/1.jpg")
, 7140), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"profile-status online pull-right\"");

WriteLiteral("></span> </div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Pavan kumar</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">Just see the my admin!</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:30 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"user-img\"");

WriteLiteral("> <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7756), Tuple.Create("\"", 7799)
, Tuple.Create(Tuple.Create("", 7762), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/2.jpg")
, 7762), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"profile-status busy pull-right\"");

WriteLiteral("></span> </div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Sonu Nigam</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">I\'ve sung a song! See you at</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:10 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"user-img\"");

WriteLiteral("> <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8381), Tuple.Create("\"", 8424)
, Tuple.Create(Tuple.Create("", 8387), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/3.jpg")
, 8387), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"profile-status away pull-right\"");

WriteLiteral("></span> </div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Arijit Sinh</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">I am a singer!</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:08 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                    <!-- Message -->\r\n" +
"                                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"user-img\"");

WriteLiteral("> <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8993), Tuple.Create("\"", 9036)
, Tuple.Create(Tuple.Create("", 8999), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/4.jpg")
, 8999), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral(" class=\"img-circle\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"profile-status offline pull-right\"");

WriteLiteral("></span> </div>\r\n                                        <div");

WriteLiteral(" class=\"mail-contnet\"");

WriteLiteral(">\r\n                                            <h5>Pavan kumar</h5> <span");

WriteLiteral(" class=\"mail-desc\"");

WriteLiteral(">Just see the my admin!</span> <span");

WriteLiteral(" class=\"time\"");

WriteLiteral(">9:02 AM</span>\r\n                                        </div>\r\n                " +
"                    </a>\r\n                                </div>\r\n              " +
"              </li>\r\n                            <li>\r\n                         " +
"       <a");

WriteLiteral(" class=\"nav-link text-center\"");

WriteLiteral(" href=\"javascript:void(0);\"");

WriteLiteral("> <strong>See all e-Mails</strong> <i");

WriteLiteral(" class=\"fa fa-angle-right\"");

WriteLiteral(@"></i> </a>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Messages -->
                <!-- ============================================================== -->
                <li");

WriteLiteral(" class=\"nav-item dropdown mega-dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral("><i");

WriteLiteral(" class=\"mdi mdi-view-grid\"");

WriteLiteral("></i></a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu animated bounceInDown\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"mega-dropdown-menu row\"");

WriteLiteral(">\r\n                            <li");

WriteLiteral(" class=\"col-lg-3 col-xlg-2 m-b-30\"");

WriteLiteral(">\r\n                                <h4");

WriteLiteral(" class=\"m-b-20\"");

WriteLiteral(">CAROUSEL</h4>\r\n                                <!-- CAROUSEL -->\r\n              " +
"                  <div");

WriteLiteral(" id=\"carouselExampleControls\"");

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(" role=\"listbox\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"carousel-item active\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral("> <img");

WriteLiteral(" class=\"d-block img-fluid\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11216), Tuple.Create("\"", 11260)
, Tuple.Create(Tuple.Create("", 11222), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/big/img1.jpg")
, 11222), false)
);

WriteLiteral(" alt=\"First slide\"");

WriteLiteral("></div>\r\n                                        </div>\r\n                        " +
"                <div");

WriteLiteral(" class=\"carousel-item\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral("><img");

WriteLiteral(" class=\"d-block img-fluid\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11502), Tuple.Create("\"", 11546)
, Tuple.Create(Tuple.Create("", 11508), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/big/img2.jpg")
, 11508), false)
);

WriteLiteral(" alt=\"Second slide\"");

WriteLiteral("></div>\r\n                                        </div>\r\n                        " +
"                <div");

WriteLiteral(" class=\"carousel-item\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral("><img");

WriteLiteral(" class=\"d-block img-fluid\"");

WriteAttribute("src", Tuple.Create(" src=\"", 11789), Tuple.Create("\"", 11833)
, Tuple.Create(Tuple.Create("", 11795), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/big/img3.jpg")
, 11795), false)
);

WriteLiteral(" alt=\"Third slide\"");

WriteLiteral("></div>\r\n                                        </div>\r\n                        " +
"            </div>\r\n                                    <a");

WriteLiteral(" class=\"carousel-control-prev\"");

WriteLiteral(" href=\"#carouselExampleControls\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"carousel-control-prev-icon\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span> <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Previous</span> </a>\r\n                                    <a");

WriteLiteral(" class=\"carousel-control-next\"");

WriteLiteral(" href=\"#carouselExampleControls\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-slide=\"next\"");

WriteLiteral("> <span");

WriteLiteral(" class=\"carousel-control-next-icon\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></span> <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Next</span> </a>\r\n                                </div>\r\n                      " +
"          <!-- End CAROUSEL -->\r\n                            </li>\r\n            " +
"                <li");

WriteLiteral(" class=\"col-lg-3 m-b-30\"");

WriteLiteral(">\r\n                                <h4");

WriteLiteral(" class=\"m-b-20\"");

WriteLiteral(">ACCORDION</h4>\r\n                                <!-- Accordian -->\r\n            " +
"                    <div");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(" class=\"nav-accordion\"");

WriteLiteral(" role=\"tablist\"");

WriteLiteral(" aria-multiselectable=\"true\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" id=\"headingOne\"");

WriteLiteral(">\r\n                                            <h5");

WriteLiteral(" class=\"mb-0\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapseOne\"");

WriteLiteral(" aria-expanded=\"true\"");

WriteLiteral(" aria-controls=\"collapseOne\"");

WriteLiteral(@">
                                                    Collapsible Group Item #1
                                                </a>
                                            </h5>
                                        </div>
                                        <div");

WriteLiteral(" id=\"collapseOne\"");

WriteLiteral(" class=\"collapse show\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"headingOne\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"card-block\"");

WriteLiteral("> Anim pariatur cliche reprehenderit, enim eiusmod high. </div>\r\n                " +
"                        </div>\r\n                                    </div>\r\n    " +
"                                <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" id=\"headingTwo\"");

WriteLiteral(">\r\n                                            <h5");

WriteLiteral(" class=\"mb-0\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"collapsed\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapseTwo\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"collapseTwo\"");

WriteLiteral(@">
                                                    Collapsible Group Item #2
                                                </a>
                                            </h5>
                                        </div>
                                        <div");

WriteLiteral(" id=\"collapseTwo\"");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"headingTwo\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"card-block\"");

WriteLiteral("> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry rich" +
"ardson ad squid. </div>\r\n                                        </div>\r\n       " +
"                             </div>\r\n                                    <div");

WriteLiteral(" class=\"card\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"card-header\"");

WriteLiteral(" role=\"tab\"");

WriteLiteral(" id=\"headingThree\"");

WriteLiteral(">\r\n                                            <h5");

WriteLiteral(" class=\"mb-0\"");

WriteLiteral(">\r\n                                                <a");

WriteLiteral(" class=\"collapsed\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-parent=\"#accordion\"");

WriteLiteral(" href=\"#collapseThree\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(" aria-controls=\"collapseThree\"");

WriteLiteral(@">
                                                    Collapsible Group Item #3
                                                </a>
                                            </h5>
                                        </div>
                                        <div");

WriteLiteral(" id=\"collapseThree\"");

WriteLiteral(" class=\"collapse\"");

WriteLiteral(" role=\"tabpanel\"");

WriteLiteral(" aria-labelledby=\"headingThree\"");

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"card-block\"");

WriteLiteral(@"> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. </div>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li");

WriteLiteral(" class=\"col-lg-3  m-b-30\"");

WriteLiteral(">\r\n                                <h4");

WriteLiteral(" class=\"m-b-20\"");

WriteLiteral(">CONTACT US</h4>\r\n                                <!-- Contact -->\r\n             " +
"                   <form>\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"exampleInputname1\"");

WriteLiteral(" placeholder=\"Enter Name\"");

WriteLiteral(">\r\n                                    </div>\r\n                                  " +
"  <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"exampleInputEmail1\"");

WriteLiteral(" placeholder=\"Enter email\"");

WriteLiteral(">\r\n                                    </div>\r\n                                  " +
"  <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <textarea");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" id=\"exampleTextarea\"");

WriteLiteral(" rows=\"3\"");

WriteLiteral(" placeholder=\"Message\"");

WriteLiteral("></textarea>\r\n                                    </div>\r\n                       " +
"             <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(">Submit</button>\r\n                                </form>\r\n                      " +
"      </li>\r\n                            <li");

WriteLiteral(" class=\"col-lg-3 col-xlg-4 m-b-30\"");

WriteLiteral(">\r\n                                <h4");

WriteLiteral(" class=\"m-b-20\"");

WriteLiteral(">List style</h4>\r\n                                <!-- List style -->\r\n          " +
"                      <ul");

WriteLiteral(" class=\"list-style-none\"");

WriteLiteral(">\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral("></i> You can give link</a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral("></i> Give link</a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral("></i> Another Give link</a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral("></i> Forth link</a></li>\r\n                                    <li><a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check text-success\"");

WriteLiteral(@"></i> Another fifth link</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- End Messages -->
                <!-- ============================================================== -->
            </ul>
            <!-- ============================================================== -->
            <!-- User profile and search -->
            <!-- ============================================================== -->
            <ul");

WriteLiteral(" class=\"navbar-nav my-lg-0\"");

WriteLiteral(">\r\n                <li");

WriteLiteral(" class=\"nav-item hidden-sm-down\"");

WriteLiteral(">\r\n                    <form");

WriteLiteral(" class=\"app-search\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" placeholder=\"Search for...\"");

WriteLiteral("> <a");

WriteLiteral(" class=\"srh-btn\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-search\"");

WriteLiteral("></i></a>\r\n                    </form>\r\n                </li>\r\n                <l" +
"i");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral(">\r\n                        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 19197), Tuple.Create("\"", 19240)
, Tuple.Create(Tuple.Create("", 19203), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/1.jpg")
, 19203), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral(" class=\"profile-pic\"");

WriteLiteral(" />\r\n                    </a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu dropdown-menu-right animated flipInY\"");

WriteLiteral(">\r\n                        <ul");

WriteLiteral(" class=\"dropdown-user\"");

WriteLiteral(">\r\n                            <li>\r\n                                <div");

WriteLiteral(" class=\"dw-user-box\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"u-img\"");

WriteLiteral("><img");

WriteAttribute("src", Tuple.Create(" src=\"", 19593), Tuple.Create("\"", 19636)
, Tuple.Create(Tuple.Create("", 19599), Tuple.Create<System.Object, System.Int32>(Href("~/lib/admin/assets/images/users/1.jpg")
, 19599), false)
);

WriteLiteral(" alt=\"user\"");

WriteLiteral("></div>\r\n                                    <div");

WriteLiteral(" class=\"u-text\"");

WriteLiteral(">\r\n                                        <h4>Steave Jobs</h4>\r\n                " +
"                        <p");

WriteLiteral(" class=\"text-muted\"");

WriteLiteral(">varun@gmail.com</p><a");

WriteLiteral(" href=\"profile.html\"");

WriteLiteral(" class=\"btn btn-rounded btn-danger btn-sm\"");

WriteLiteral(">View Profile</a>\r\n                                    </div>\r\n                  " +
"              </div>\r\n                            </li>\r\n                       " +
"     <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-user\"");

WriteLiteral("></i> My Profile</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-wallet\"");

WriteLiteral("></i> My Balance</a></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-email\"");

WriteLiteral("></i> Inbox</a></li>\r\n                            <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"ti-settings\"");

WriteLiteral("></i> Account Setting</a></li>\r\n                            <li");

WriteLiteral(" role=\"separator\"");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                            <li><a");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-power-off\"");

WriteLiteral("></i> Logout</a></li>\r\n                        </ul>\r\n                    </div>\r" +
"\n                </li>\r\n                <li");

WriteLiteral(" class=\"nav-item dropdown\"");

WriteLiteral(">\r\n                    <a");

WriteLiteral(" class=\"nav-link dropdown-toggle text-muted waves-effect waves-dark\"");

WriteLiteral(" href=\"\"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" aria-haspopup=\"true\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteLiteral("> <i");

WriteLiteral(" class=\"flag-icon flag-icon-us\"");

WriteLiteral("></i></a>\r\n                    <div");

WriteLiteral(" class=\"dropdown-menu  dropdown-menu-right animated bounceInDown\"");

WriteLiteral("> <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flag-icon flag-icon-in\"");

WriteLiteral("></i> India</a> <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flag-icon flag-icon-fr\"");

WriteLiteral("></i> French</a> <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flag-icon flag-icon-cn\"");

WriteLiteral("></i> China</a> <a");

WriteLiteral(" class=\"dropdown-item\"");

WriteLiteral(" href=\"#\"");

WriteLiteral("><i");

WriteLiteral(" class=\"flag-icon flag-icon-de\"");

WriteLiteral("></i> Dutch</a> </div>\r\n                </li>\r\n            </ul>\r\n        </div>\r" +
"\n    </nav>\r\n</header>\r\n");

        }
    }
}
#pragma warning restore 1591
