#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_Layout.cshtml")]
    public partial class _Areas_Admin_Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
  
    Layout = "_Root.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\r\n<section>\r\n    <div");

WriteLiteral(" class=\"content-wrapper\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"page-header\"");

WriteLiteral(">\r\n                <h2>");

            
            #line 8 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
               Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

WriteLiteral("                ");

            
            #line 9 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
           Write(RenderSection("breadcrumb", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

WriteLiteral("            ");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n</section>\r\n\r\n");

DefineSection("script", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 17 "..\..\Areas\Admin\Views\Shared\_Layout.cshtml"
Write(RenderSection("script", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
