#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/_LeftSideBar.cshtml")]
    public partial class _Areas_Admin_Views_Shared__LeftSideBar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Admin_Views_Shared__LeftSideBar_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<aside");

WriteLiteral(" class=\"aside\"");

WriteLiteral(">\r\n    <!-- START Sidebar (left)-->\r\n    <div");

WriteLiteral(" class=\"aside-inner\"");

WriteLiteral(">\r\n        <nav");

WriteLiteral(" data-sidebar-anyclick-close=\"\"");

WriteLiteral(" class=\"sidebar\"");

WriteLiteral(">\r\n            <!-- START sidebar nav-->\r\n            <ul");

WriteLiteral(" class=\"nav menu\"");

WriteLiteral(">\r\n                <!-- Iterates over all sidebar items-->\r\n                <li");

WriteLiteral(" class=\"nav-heading \"");

WriteLiteral(">\r\n                    <h4>WEB CONTENTS</h4>\r\n                </li>\r\n");

            
            #line 11 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
                
            
            #line default
            #line hidden
            
            #line 11 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
                 foreach (var item in ModelManager.ModelManagerMapper)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 533), Tuple.Create("\"", 613)
            
            #line 14 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
, Tuple.Create(Tuple.Create("", 540), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","ModelManagement",new { @area=G.AdminPath,@id=item })
            
            #line default
            #line hidden
, 540), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 614), Tuple.Create("\"", 627)
            
            #line 14 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
                                    , Tuple.Create(Tuple.Create("", 622), Tuple.Create<System.Object, System.Int32>(item
            
            #line default
            #line hidden
, 622), false)
);

WriteLiteral(">\r\n                            <em");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(">description</em>\r\n                            <span>");

            
            #line 16 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
                             Write(item.GetModelTitle());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </a>\r\n                    </li>\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <hr />\r\n                </li>\r\n        " +
"        <li");

WriteLiteral(" class=\"nav-heading \"");

WriteLiteral(">\r\n                    <h4>Roles And Users</h4>\r\n                </li>\r\n         " +
"       <li>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1073), Tuple.Create("\"", 1134)
            
            #line 27 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1080), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Roles",new { @area=G.AdminPath })
            
            #line default
            #line hidden
, 1080), false)
);

WriteLiteral(" title=\"Management User\"");

WriteLiteral(">\r\n                        <em");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(">account_box</em>\r\n                        <span>Manage Role And User</span>\r\n   " +
"                 </a>\r\n                </li>\r\n                <li");

WriteLiteral(" class=\"nav-heading \"");

WriteLiteral(">\r\n                    <h4>LogOff</h4>\r\n                </li>\r\n                <l" +
"i>\r\n                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1486), Tuple.Create("\"", 1541)
            
            #line 36 "..\..\Areas\Admin\Views\Shared\_LeftSideBar.cshtml"
, Tuple.Create(Tuple.Create("", 1493), Tuple.Create<System.Object, System.Int32>(Url.Action("LogOff","Account",new { @area="" })
            
            #line default
            #line hidden
, 1493), false)
);

WriteLiteral(" title=\"Management User\"");

WriteLiteral(">\r\n                        <em");

WriteLiteral(" class=\"material-icons\"");

WriteLiteral(">power_settings_new</em>\r\n                        <span>LogOff System</span>\r\n   " +
"                 </a>\r\n                </li>\r\n            </ul>\r\n            <!-" +
"- END sidebar nav-->\r\n        </nav>\r\n    </div>\r\n    <!-- #END# Sidebar (left)-" +
"->\r\n</aside>");

        }
    }
}
#pragma warning restore 1591
