#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using SDHC.Common.Entity;
    
    #line 1 "..\..\Areas\Admin\Views\Shared\AdminInputs\_PropertiesEdit.cshtml"
    using SDHC.Common.Entity.Models;
    
    #line default
    #line hidden
    using WebSQL;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Shared/AdminInputs/_PropertiesEdit.cshtml")]
    public partial class _Areas_Admin_Views_Shared_AdminInputs__PropertiesEdit_cshtml : System.Web.Mvc.WebViewPage<IPassModel>
    {
        public _Areas_Admin_Views_Shared_AdminInputs__PropertiesEdit_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Shared\AdminInputs\_PropertiesEdit.cshtml"
  
    var index = 0;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 6 "..\..\Areas\Admin\Views\Shared\AdminInputs\_PropertiesEdit.cshtml"
 foreach (var property in Model.Properties)
{
    Html.RenderPartial("AdminInputs/_AdminInput", new ContentPropertyIndex(property, index));
    index++;
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
